import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

type R = Record<string, any>;
const WEBAPP_URL = (import.meta.env.VITE_GOOGLE_SCRIPT_WEBAPP_URL || '') as string;
const CP = '본 실습은 교육용 가상 자료만 사용합니다. 실제 고객명, 병원명, 의료진명, 제품명, 매출·처방 정보, 내부 수치, 민감정보는 입력하지 마세요.';
const screens = ['입장과 AI 안전선','좋은 질문 만들기','Dashboard Reading','MR별 실행행동 Map','이해관계자 메시지 번역','성과대화 AI 답변 감별','고객관점 콜플랜 요청','본사 요청 현장 번역','MR 1on1 코칭','7일·30일 실행계획'];
const metricOrder = ['콜실행률','담당처커버리지','CRM기록충실도','후속조치율','고객반응지수','성과전환지수','팀기여지수','실행지연'];
const metricGroups = [
  ['선행 활동','콜실행률 / 담당처커버리지','성과 신호가 만들어질 기회 자체를 봅니다.'],
  ['과정 품질','CRM기록충실도 / 후속조치율 / 실행지연','활동이 고객가치와 후속 실행으로 이어지는지 봅니다.'],
  ['고객 반응','고객반응지수','고객이 의미 있게 반응하는지 봅니다.'],
  ['결과 신호','성과 신호 전환지수','활동과 반응이 성과 신호로 연결되는지 봅니다.'],
  ['조직 확산','팀기여지수','개인 경험이 팀 학습과 협업으로 확산되는지 봅니다.']
];
const members = [
  { id:'M01', name:'신재영 대리', type:'활동량 과다·성과전환 저조형', signal:'콜 실행률은 높지만 후속조치율과 성과전환지수가 낮다. 활동량보다 접점 목적과 후속 실행 품질 점검이 필요하다.', comment:'저는 누구보다 많이 움직이고 있습니다.', metrics:{콜실행률:112, 담당처커버리지:96, CRM기록충실도:64, 후속조치율:58, 고객반응지수:62, 성과전환지수:54, 팀기여지수:61, 실행지연:2}},
  { id:'M02', name:'이대은 대리', type:'고성과 개인플레이형', signal:'성과전환지수와 고객반응지수는 높지만 팀기여지수가 낮다. 개인성과 인정과 팀 기여 요청의 균형이 필요하다.', comment:'각자 자기 담당처는 본인이 책임지는 게 맞지 않나요?', metrics:{콜실행률:91, 담당처커버리지:88, CRM기록충실도:72, 후속조치율:74, 고객반응지수:84, 성과전환지수:128, 팀기여지수:42, 실행지연:1}},
  { id:'M03', name:'박재욱 사원', type:'신입 위축형', signal:'CRM 기록은 성실하지만 콜 실행률과 고객반응지수가 낮다. 신입 위축과 접점 전 준비 부족 가능성을 확인해야 한다.', comment:'제가 가면 오히려 불편해하시는 것 같습니다.', metrics:{콜실행률:72, 담당처커버리지:69, CRM기록충실도:90, 후속조치율:67, 고객반응지수:51, 성과전환지수:48, 팀기여지수:70, 실행지연:1}},
  { id:'M04', name:'유희관 과장', type:'경력 안정형', signal:'담당처 관계와 고객반응은 안정적이나 CRM 기록과 캠페인 실행이 낮다. 변화 요구를 현장 언어로 연결해야 한다.', comment:'현장에서는 그런 방식이 잘 안 맞습니다.', metrics:{콜실행률:86, 담당처커버리지:92, CRM기록충실도:55, 후속조치율:63, 고객반응지수:76, 성과전환지수:82, 팀기여지수:58, 실행지연:3}},
  { id:'M05', name:'김문호 차장', type:'방어적 목표미달형', signal:'목표진척과 실행 속도가 모두 낮다. 외부 요인 탓으로 단정하거나 반박하기보다 데이터 기반 공동 진단이 필요하다.', comment:'이번 지역 상황은 제가 어떻게 할 수 있는 게 아닙니다.', metrics:{콜실행률:79, 담당처커버리지:75, CRM기록충실도:68, 후속조치율:61, 고객반응지수:60, 성과전환지수:68, 팀기여지수:55, 실행지연:5}},
  { id:'M06', name:'김재호 차장', type:'실행지연·CRM 부실형', signal:'콜 실행은 유지되지만 CRM 기록과 후속조치율이 낮다. 완료 기준과 사후보고 기준 명확화가 필요하다.', comment:'현장 대응하느라 입력은 나중에 하게 됩니다.', metrics:{콜실행률:93, 담당처커버리지:81, CRM기록충실도:41, 후속조치율:45, 고객반응지수:69, 성과전환지수:73, 팀기여지수:62, 실행지연:4}}
];
const intuitionOptions = ['활동량 부족','접점 품질 문제','후속조치 문제','자신감 부족','개인플레이 문제','변화 저항','실행관리 문제','판단 유보'];
const altOptions = ['담당 고객군 난이도','지역 상황','캠페인 메시지 부적합','팀장 기준 미제시','신입 적응 단계','기록 방식 문제','단기 성과 측정 한계'];
const gaps = ['접점 목적 불명확','후속조치 미흡','고객군 우선순위 문제','메시지 일관성 부족','동기 저하','팀장 지원 필요'];
const customers = ['고객군 A: 접점 낮음·반응 높음·성장 가능성 높음','고객군 B: 접점 높음·반응 낮음·메시지 재설계 필요','고객군 C: 후속조치 필요 높음·신뢰 리스크 높음','고객군 D: 접점 낮음·탐색적 관계 형성 필요'];
const parseKeys = [
  ['causalHypotheses','가능한 인과 가설 3개','## 1. 가능한 인과 가설 3개'],
  ['counterHypotheses','이 해석이 틀렸을 가능성 3개','## 2. 이 해석이 틀렸을 가능성 3개'],
  ['confirmationQuestions','팀장이 확인해야 할 질문 5개','## 3. 팀장이 확인해야 할 질문 5개'],
  ['twoWeekExperiments','2주 동안 검증할 작은 실행 실험 2개','## 4. 2주 동안 검증할 작은 실행 실험 2개'],
  ['cautions','성급한 판단을 피하기 위한 주의점','## 5. 성급한 판단을 피하기 위한 주의점']
] as const;
const requiredPlan = [['priorityInterpretation','내가 우선 확인할 해석'],['confirmQuestion','팀원에게 던질 확인 질문'],['twoWeekCommitment','이번 2주 실행 약속'],['recheckEvidence','2주 후 점검할 지표/증거']];
const optionalPlan = [['recheckData','다시 확인할 데이터'],['expectedBehaviorSignal','먼저 달라져야 할 행동 신호'],['expectedResultSignal','이후 기대할 결과 신호']];
function getJson<T>(k:string,i:T):T{try{return JSON.parse(localStorage.getItem(k)||'null')??i}catch{return i}}
function useStore<T>(k:string,i:T){const[v,s]=useState<T>(()=>getJson(k,i));useEffect(()=>localStorage.setItem(k,JSON.stringify(v)),[k,v]);return[v,s] as const}
function Card({children,className=''}:any){return <div className={'rounded-2xl border bg-white p-5 shadow-sm '+className}>{children}</div>}
function Guide({title,children,tone='cyan'}:any){return <div className={(tone==='orange'?'bg-orange-50':'bg-cyan-50')+' rounded-xl p-3 text-sm'}><b>{title}</b><div className='mt-1 text-slate-700'>{children}</div></div>}
function Field({label,value,onChange,rows=3,placeholder=''}:any){return <label className='block'><b className='text-sm'>{label}</b><textarea className='mt-1 w-full rounded-xl border p-3' rows={rows} placeholder={placeholder} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function metricLabel(k:string){return k==='성과전환지수'?'성과 신호 전환지수':k}
function member(id:string){return members.find(m=>m.id===id)||members[0]}
function toggle(arr:string[], v:string){return arr.includes(v)?arr.filter(x=>x!==v):[...arr,v]}
function firstLine(s:string){return (s||'').split('\n').map(x=>x.trim()).filter(x=>x && !x.startsWith('#'))[0]||''}
function level(k:string,v:any){if(k==='실행지연') return Number(v)>=4?'주의':Number(v)>=2?'관찰':'양호'; if(v>=110)return'강점'; if(v>=90)return'기준권'; if(v>=70)return'관찰'; return'주의'}
function parseAi(text:string):R{const out:R={causalHypotheses:'',counterHypotheses:'',confirmationQuestions:'',twoWeekExperiments:'',cautions:''};const t=(text||'').replace(/\r/g,'').trim();if(!t)return out;const hits=parseKeys.map(([key,label,title])=>({key,title,idx:t.indexOf(title)})).filter(x=>x.idx>=0).sort((a,b)=>a.idx-b.idx);if(hits.length>1){hits.forEach((h,i)=>{out[h.key]=t.slice(h.idx,hits[i+1]?.idx??t.length).trim()});return out;}const lines=t.split('\n').map(x=>x.trim()).filter(Boolean);out.causalHypotheses=lines.filter(x=>/가설|가능성|원인/.test(x)).slice(0,8).join('\n');out.counterHypotheses=lines.filter(x=>/대안|틀렸|반대|한계|난이도|지역|캠페인/.test(x)).slice(0,8).join('\n');out.confirmationQuestions=lines.filter(x=>/\?|질문|확인/.test(x)).slice(0,8).join('\n');out.twoWeekExperiments=lines.filter(x=>/2주|실험|행동|지원|지표|증거/.test(x)).slice(0,10).join('\n');out.cautions=lines.filter(x=>/주의|단정|성급|확정/.test(x)).slice(0,6).join('\n');return out}
function buildPrompt(m:R,metrics:R,causal:string,alts:string[],intuition:string,evidence:string[],plan:R){const metricLines=metricOrder.map(k=>`${metricLabel(k)}: ${metrics[k]}`).join('\n');return `당신은 제약영업팀장의 데이터 기반 성과진단을 돕는 리더십 코치입니다.\n\n아래 데이터는 교육용 가상 데이터입니다. 실제 고객명, 병원명, 의료진명, 제품명, 매출, 처방 정보는 포함하지 않습니다. 절대 실제 영업전략, 처방 유도, 고객 공략 표현을 사용하지 마세요.\n\n당신의 역할은 팀원을 평가하거나 문제 직원으로 판정하는 것이 아닙니다. 팀장이 자신의 직관을 데이터 기반 인과 가설로 바꾸고, 팀원과 확인할 질문과 2주 검증 행동을 설계하도록 돕는 것입니다.\n\n[팀원]\n${m.name} / ${m.type}\n\n[지표]\n${metricLines}\n\n[나의 직관적 판단]\n${intuition||'판단 유보'}\n\n[판단 근거 지표]\n${evidence.map(metricLabel).join(', ')||'미선택'}\n\n[나의 1차 인과 가설]\n${causal||'작성 전'}\n\n[대안 가설]\n${alts.join(', ')||'작성 전'}\n\n[2주 실행 약속 초안]\n${plan.twoWeekCommitment||'작성 전'}\n\n[요청]\n아래 출력 형식을 반드시 지켜주세요. 표를 사용하지 말고, 각 항목의 제목을 그대로 유지하세요. 모든 표현은 단정형이 아니라 “가능성이 있다”, “확인할 필요가 있다”로 작성하세요.\n\n## 1. 가능한 인과 가설 3개\n\n1) 가설:\n- 근거 지표:\n- 그렇게 볼 수 있는 이유:\n- 아직 확인해야 할 점:\n\n2) 가설:\n- 근거 지표:\n- 그렇게 볼 수 있는 이유:\n- 아직 확인해야 할 점:\n\n3) 가설:\n- 근거 지표:\n- 그렇게 볼 수 있는 이유:\n- 아직 확인해야 할 점:\n\n## 2. 이 해석이 틀렸을 가능성 3개\n\n1) 대안 가능성:\n- 왜 그럴 수 있는가:\n- 확인해야 할 데이터 또는 질문:\n\n2) 대안 가능성:\n- 왜 그럴 수 있는가:\n- 확인해야 할 데이터 또는 질문:\n\n3) 대안 가능성:\n- 왜 그럴 수 있는가:\n- 확인해야 할 데이터 또는 질문:\n\n## 3. 팀장이 확인해야 할 질문 5개\n\n질문은 팀원을 몰아붙이는 방식이 아니라, 사실 확인, 맥락 이해, 공동 진단, 다음 행동 합의를 돕는 톤으로 작성하세요.\n\n1)\n2)\n3)\n4)\n5)\n\n## 4. 2주 동안 검증할 작은 실행 실험 2개\n\n1) 실행 실험:\n- 목적:\n- 구체 행동:\n- 팀장의 지원:\n- 2주 후 확인할 지표/증거:\n\n2) 실행 실험:\n- 목적:\n- 구체 행동:\n- 팀장의 지원:\n- 2주 후 확인할 지표/증거:\n\n## 5. 성급한 판단을 피하기 위한 주의점\n\n- 낮은 지표를 사람의 역량 문제로 바로 단정하지 마세요.\n- 단면 데이터만으로 인과관계를 확정하지 마세요.\n- 팀원의 설명을 듣기 전까지는 가설로만 다루세요.\n- AI 답변은 최종 판단이 아니라 팀장의 검토 자료입니다.`}
function shareCardText(state:R, currentMember?:R){return `[조별 공유 카드]\n선택 팀원: ${currentMember?.name||member(state.selectedMemberId).name}\n처음 든 판단: ${state.intuitionJudgment||'-'}\n근거 지표: ${(state.evidenceMetrics||[]).map(metricLabel).join(', ')||'-'}\n우선 확인할 해석: ${state.priorityInterpretation||state.causalHypothesis||'-'}\n팀원에게 던질 질문: ${state.confirmQuestion||'-'}\n2주 실행 약속: ${state.twoWeekCommitment||'-'}\n2주 후 점검할 지표/증거: ${state.recheckEvidence||'-'}`}
function ShareCard({state,currentMember}:any){const text=shareCardText(state,currentMember);return <Card className='border-cyan-200'><h3 className='font-bold'>조별 공유 카드</h3><Guide title='조별 공유 방법'>개인 실습 후 이 카드만 보고 2분 이내로 공유하세요. 발표가 아니라 서로 다른 팀원 유형을 비교하는 토의 자료입니다.</Guide><pre className='preline mt-3 rounded-xl bg-slate-100 p-3 text-sm'>{text}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>navigator.clipboard?.writeText(text)}>공유 카드 복사</button></Card>}
async function callGoogle(action:string,payload:R={}){if(!WEBAPP_URL)throw new Error('no url');const r=await fetch(WEBAPP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'failed');return j.data}
function App(){const[step,setStep]=useStore('c1bio_flow_step',0);const[participant,setParticipant]=useStore<R>('c1bio_flow_participant',{participantId:'P-'+Date.now(),sessionCode:'C1BIO-1차',name:'',teamName:''});const[state,setState]=useStore<R>('c1bio_flow_state',{selectedMemberId:'M01'});const[status,setStatus]=useState('localStorage 저장됨');async function save(key:string,patch:R){const next={...state,...patch,responses:{...(state.responses||{}),[key]:patch}};setState(next);if(WEBAPP_URL){try{await callGoogle('saveResponse',{responseId:'R-'+Date.now(),participantId:participant.participantId,sessionCode:participant.sessionCode,teamName:participant.teamName,screenId:'J'+String(step+1).padStart(2,'0'),activityId:key,activityName:screens[step],outputData:patch,promptText:patch.generatedPrompt||'',aiAnswerText:patch.aiAnswerRaw||'',reviewData:patch.aiParsed||{},finalText:JSON.stringify(patch),isCompleted:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setStatus('Google Sheets 저장됨')}catch{setStatus('Google 저장 실패 · localStorage 유지')}}}
return <div className='mx-auto max-w-7xl p-5'><header className='mb-5 flex justify-between gap-3'><div><h1 className='text-2xl font-bold'>C1바이오 Full Flow Journey</h1><p className='text-slate-600'>J{String(step+1).padStart(2,'0')} · {screens[step]} · {Math.round((step+1)/screens.length*100)}%</p></div><div className='flex gap-2'><button className='rounded-xl border px-4 py-2' onClick={()=>location.href='/'}>기존 MVP</button><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>location.href='/instructor-live.html'}>Live Dashboard</button></div></header><div className='safe mb-4 rounded-xl px-4 py-3 text-sm font-medium'>{CP}</div><div className='mb-4 h-2 rounded-full bg-slate-200'><div className='h-2 rounded-full bg-cyan-700' style={{width:((step+1)/screens.length*100)+'%'}}/></div>{step===0&&<Entry participant={participant} setParticipant={setParticipant} save={save}/>} {step===1&&<PromptLab save={save}/>} {step===2&&<Dashboard state={state} save={save}/>} {step===3&&<ActionMap state={state} save={save}/>} {step===4&&<Stakeholder state={state} save={save}/>} {step===5&&<Review state={state} save={save}/>} {step===6&&<CallPlan state={state} save={save}/>} {step===7&&<Hq save={save}/>} {step===8&&<OneOnOne state={state} save={save}/>} {step===9&&<Wrap state={state} save={save}/>}<footer className='sticky bottom-0 mt-6 flex justify-between rounded-2xl border bg-white/90 p-3'><button className='rounded-xl border px-5 py-3' onClick={()=>setStep(Math.max(0,step-1))}>이전</button><span className='py-3 text-sm'>{status}</span><button className='rounded-xl bg-cyan-700 px-5 py-3 text-white' onClick={()=>setStep(Math.min(screens.length-1,step+1))}>저장하고 다음</button></footer></div>}
function Entry({participant,setParticipant,save}:any){return <Card><h2 className='text-xl font-bold'>입장</h2><Guide title='조별 운영 안내'>같은 조 안에서는 서로 다른 팀원을 맡아 진행합니다. 이후 조별 공유 카드로 서로의 판단과 실행 약속을 비교합니다.</Guide><div className='mt-4 grid gap-3 md:grid-cols-3'>{[['sessionCode','세션코드'],['name','이름'],['teamName','팀명']].map(([k,l])=><label key={k}><b>{l}</b><input className='mt-1 w-full rounded-xl border p-3' value={participant[k]} onChange={e=>setParticipant({...participant,[k]:e.target.value})}/></label>)}</div><button className='mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J01-entry',{consentChecked:true,finalText:'AI 안전선 확인'})}>확인 저장</button></Card>}
function PromptLab({save}:any){const[prompt,setPrompt]=useState('역할: 당신은 영업팀장의 업무관리 코치입니다.\n상황: 교육용 가상 데이터입니다.\n요청: 모호한 업무 지시를 고객 신뢰, 접점 품질, 후속조치 기준이 포함된 실행 요청문으로 바꿔주세요.');return <Card><h2 className='text-xl font-bold'>좋은 질문 만들기</h2><Guide title='해야 할 일'>나쁜 질문을 안전하고 구체적인 AI 질문으로 바꿔보세요.</Guide><p className='mt-3 rounded-xl bg-orange-50 p-3'>나쁜 질문: 고객관리 더 신경 쓰라고 말하고 싶은데 어떻게 하죠?</p><Field label='안전한 프롬프트' rows={8} value={prompt} onChange={setPrompt}/><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>{navigator.clipboard?.writeText(prompt);save('J02-prompt',{generatedPrompt:prompt})}}>복사 및 저장</button></Card>}
function Dashboard({state,save}:any){const[id,setId]=useState(state.selectedMemberId||'M01');const m=member(id);const metrics=m.metrics;const[intuition,setIntuition]=useState(state.intuitionJudgment||'');const[evidence,setEvidence]=useState<string[]>(state.evidenceMetrics||[]);const[leading,setLeading]=useState(state.leadingMetric||'콜실행률');const[process,setProcess]=useState(state.processMetric||'후속조치율');const[response,setResponse]=useState(state.responseMetric||'고객반응지수');const[result,setResult]=useState(state.resultMetric||'성과전환지수');const[causal,setCausal]=useState(state.causalHypothesis||`${leading}와 ${process}의 연결을 볼 때, ${response}가 충분히 형성되지 못했고 그 결과 ${metricLabel(result)}가 낮아졌을 가능성이 있다.`);const[alts,setAlts]=useState<string[]>(state.alternativeHypotheses||[]);const[altText,setAltText]=useState(state.alternativeHypothesisText||'');const[aiRaw,setAiRaw]=useState(state.aiAnswerRaw||'');const[aiParsed,setAiParsed]=useState<R>(state.aiParsed||{});const[plan,setPlan]=useState<R>({priorityInterpretation:state.priorityInterpretation||'',confirmQuestion:state.confirmQuestion||'',twoWeekCommitment:state.twoWeekCommitment||'',recheckEvidence:state.recheckEvidence||'',recheckData:state.recheckData||'',expectedBehaviorSignal:state.expectedBehaviorSignal||'',expectedResultSignal:state.expectedResultSignal||''});const[selGaps,setGaps]=useState<string[]>(state.gapHypotheses||[]);const[q,setQ]=useState(state.confirmationQuestion||'');const aiPrompt=useMemo(()=>buildPrompt(m,metrics,causal,alts,intuition,evidence,plan),[m,metrics,causal,alts,intuition,evidence,plan]);const shareState={...state,selectedMemberId:id,intuitionJudgment:intuition,evidenceMetrics:evidence,causalHypothesis:causal,...plan};function fillDraft(){setPlan({...plan,priorityInterpretation:firstLine(aiParsed.causalHypotheses)||causal,confirmQuestion:firstLine(aiParsed.confirmationQuestions)||q,twoWeekCommitment:firstLine(aiParsed.twoWeekExperiments)||plan.twoWeekCommitment,recheckEvidence:plan.recheckEvidence||'후속조치율, 고객반응지수, 성과 신호 전환지수',recheckData:plan.recheckData||evidence.map(metricLabel).join(', '),expectedBehaviorSignal:plan.expectedBehaviorSignal||'후속조치 이행률과 CRM 기록 충실도 개선',expectedResultSignal:plan.expectedResultSignal||'고객 반응 지수와 성과 신호 전환지수 개선 가능성'});}function saveDashboard(){save('J03-dashboard',{selectedMemberId:id,dataSignal:m.signal,intuitionJudgment:intuition,evidenceMetrics:evidence,leadingMetric:leading,processMetric:process,responseMetric:response,resultMetric:result,causalHypothesis:causal,alternativeHypotheses:alts,alternativeHypothesisText:altText,generatedPrompt:aiPrompt,aiAnswerRaw:aiRaw,aiParsed,gapHypotheses:selGaps,confirmationQuestion:q,...plan,shareCard:shareCardText(shareState,m)});}
return <div className='grid gap-4'><Card className='border-cyan-200 bg-cyan-50'><h2 className='text-2xl font-bold'>오늘의 미션: 팀원 1명의 2주 행동 실험안 만들기</h2><p className='mt-2'>같은 조 안에서는 서로 다른 팀원을 맡습니다. 개인 실습 후 조별 공유 카드로 결과를 비교합니다.</p><div className='mt-4 grid gap-2 md:grid-cols-4'>{['우선 확인할 해석','팀원에게 던질 질문','2주 실행 약속','2주 후 점검 지표/증거'].map(x=><div key={x} className='rounded-xl bg-white p-3 text-sm font-semibold'>완성물 · {x}</div>)}</div></Card>
<Card><h3 className='font-bold'>0. 팀원 1명 선택하기</h3><Guide title='조별 실습 안내'>조원끼리 먼저 담당 팀원을 나눈 뒤 선택하세요. 같은 조에서는 가능한 한 중복 선택하지 않습니다.</Guide><select className='mt-3 w-full rounded-xl border p-3' value={id} onChange={e=>setId(e.target.value)}>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.type}</option>)}</select></Card>
<Card><h3 className='font-bold'>1. 지표 사이에서 끊긴 연결 찾기</h3><Guide title='해야 할 일'>지표를 하나씩 평가하지 말고, 지표 사이의 불일치를 찾으세요.</Guide><div className='mt-3 grid grid-cols-1 gap-2 md:grid-cols-4'>{metricOrder.map(k=><div key={k} className='rounded-xl bg-slate-50 p-3'><div className='flex justify-between gap-2'><p className='text-xs font-semibold'>{metricLabel(k)}</p><span className='rounded-full bg-white px-2 py-1 text-[11px]'>{level(k,metrics[k])}</span></div><b className='text-xl'>{metrics[k]}</b></div>)}</div><p className='mt-3 rounded-xl bg-slate-50 p-3'>{m.signal}</p></Card>
<Card><h3 className='font-bold'>지표 연결 지도</h3><Guide title='보는 법'>성과 신호가 낮다면 어느 연결고리에서 끊겼는지 찾으세요. 원인 확정이 아니라 확인 질문을 만들기 위한 틀입니다.</Guide><div className='mt-3 grid gap-3 md:grid-cols-5'>{metricGroups.map(([a,b,c])=><div key={a} className='rounded-xl border p-3'><b>{a}</b><p className='mt-1 text-sm'>{b}</p><p className='mt-2 text-xs text-slate-500'>{c}</p></div>)}</div></Card>
<Card><h3 className='font-bold'>2. 처음 든 판단 선택하기</h3><Guide title='해야 할 일'>데이터를 본 순간 떠오른 첫 판단을 하나 선택하세요. 정답이 아니라 검증할 출발점입니다.</Guide><div className='mt-3 flex flex-wrap gap-2'>{intuitionOptions.map(o=><button key={o} className={'rounded-xl border px-3 py-2 text-sm '+(intuition===o?'bg-cyan-700 text-white':'')} onClick={()=>setIntuition(o)}>{o}</button>)}</div></Card>
<Card><h3 className='font-bold'>3. 그 판단의 데이터 근거 고르기</h3><Guide title='해야 할 일'>내 직관을 뒷받침하거나 흔드는 지표를 2~3개만 선택하세요.</Guide><div className='mt-3 flex flex-wrap gap-2'>{metricOrder.map(o=><button key={o} className={'rounded-xl border px-3 py-2 text-sm '+(evidence.includes(o)?'bg-cyan-700 text-white':'')} onClick={()=>setEvidence(toggle(evidence,o))}>{metricLabel(o)}</button>)}</div></Card>
<Card><h3 className='font-bold'>4. 왜 이런 결과가 나왔는지 가설 쓰기</h3><Guide title='해야 할 일'>선행지표→과정지표→결과지표 연결을 한 문장으로 쓰세요. 단정하지 말고 “가능성이 있다”로 표현하세요.</Guide><div className='mt-3 grid gap-3 md:grid-cols-4'>{[['선행지표',leading,setLeading,['콜실행률','담당처커버리지']],['과정지표',process,setProcess,['CRM기록충실도','후속조치율','실행지연']],['반응지표',response,setResponse,['고객반응지수']],['결과지표',result,setResult,['성과전환지수','팀기여지수']]].map(([label,value,setter,opts]:any)=><label key={label}><b className='text-sm'>{label}</b><select className='mt-1 w-full rounded-xl border p-3' value={value} onChange={e=>setter(e.target.value)}>{opts.map((o:string)=><option key={o} value={o}>{metricLabel(o)}</option>)}</select></label>)}</div><Field label='내가 작성한 인과 가설' value={causal} onChange={setCausal} rows={4}/></Card>
<Card><h3 className='font-bold'>5. 내 해석이 틀렸을 가능성 확인하기</h3><Guide title='해야 할 일'>최소 1개 이상 선택하세요. 데이터로 단정하지 않고, 데이터로 더 좋은 질문을 만듭니다.</Guide><div className='mt-3 flex flex-wrap gap-2'>{altOptions.map(o=><button key={o} className={'rounded-xl border px-3 py-2 text-sm '+(alts.includes(o)?'bg-cyan-700 text-white':'')} onClick={()=>setAlts(toggle(alts,o))}>{o}</button>)}</div><Field label='직접 작성할 대안 가설' value={altText} onChange={setAltText} rows={3}/></Card>
<Card><h3 className='font-bold'>6. AI에게 내 판단 점검받기</h3><Guide title='해야 할 일'>아래 프롬프트를 복사해 AI 도구에 붙여넣으세요. 정답을 묻는 것이 아니라, 내 가설의 빈틈과 확인 질문을 점검받는 단계입니다.</Guide><pre className='preline mt-3 max-h-72 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{aiPrompt}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>navigator.clipboard?.writeText(aiPrompt)}>AI 검증 프롬프트 복사</button></Card>
<Card><h3 className='font-bold'>7. AI 답변을 붙여넣고 나눠보기</h3><Guide title='해야 할 일' tone='orange'>AI 답변 전체를 붙여넣고 ‘항목별 분리’를 누르세요. 분리된 내용은 팀장 관점에서 수정하세요.</Guide><Field label='AI 답변 원문 붙여넣기' value={aiRaw} onChange={setAiRaw} rows={8}/><button className='mt-2 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>setAiParsed(parseAi(aiRaw))}>항목별 분리</button><div className='mt-4 grid gap-3 md:grid-cols-2'>{parseKeys.map(([key,label])=><Field key={key} label={label} value={aiParsed[key]} onChange={(v:string)=>setAiParsed({...aiParsed,[key]:v})} rows={5}/>)}</div></Card>
<Card><h3 className='font-bold'>8. 팀원과 2주 동안 해볼 행동 정하기</h3><Guide title='완료 기준'>필수 4개가 완성되면 조별 공유가 가능합니다. AI 제안을 그대로 실행하지 말고 현실적인 해석 1개와 실행 행동 1개를 선택하세요.</Guide><button className='my-4 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={fillDraft}>AI 제안으로 초안 채우기</button><h4 className='font-bold'>필수 입력</h4><div className='mt-2 grid gap-3 md:grid-cols-2'>{requiredPlan.map(([k,l])=><Field key={k} label={l} value={plan[k]} onChange={(v:string)=>setPlan({...plan,[k]:v})} rows={3}/>)}</div><h4 className='mt-5 font-bold'>선택 입력</h4><div className='mt-2 grid gap-3 md:grid-cols-3'>{optionalPlan.map(([k,l])=><Field key={k} label={l} value={plan[k]} onChange={(v:string)=>setPlan({...plan,[k]:v})} rows={3}/>)}</div></Card>
<ShareCard state={shareState} currentMember={m}/>
<Card><h3 className='font-bold'>9. 저장 전 마지막 확인</h3><Guide title='체크리스트'>□ 우선 확인할 해석을 정했다 · □ 팀원에게 던질 확인 질문을 정했다 · □ 2주 실행 약속을 정했다 · □ 2주 후 확인할 지표/증거를 정했다</Guide><div className='mt-3 flex flex-wrap gap-2'>{gaps.map(g=><button key={g} className={'rounded-xl border px-3 py-2 '+(selGaps.includes(g)?'bg-cyan-700 text-white':'')} onClick={()=>setGaps(toggle(selGaps,g))}>{g}</button>)}</div><Field label='추가 확인 질문' value={q} onChange={setQ}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={saveDashboard}>Dashboard 판단 저장</button></Card></div>}
function ActionMap({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({fact:state.priorityInterpretation||state.causalHypothesis||m.signal,action:state.twoWeekCommitment||'',support:'',promise:state.recheckEvidence||''});return <Card><h2 className='text-xl font-bold'>{m.name} 실행행동 Map</h2><Guide title='해야 할 일'>Dashboard에서 만든 해석과 2주 실행 약속을 실제 행동 Map으로 바꾸세요.</Guide><p className='mt-3 rounded-xl bg-slate-50 p-3'>우선 확인할 해석: {state.priorityInterpretation||'-'}<br/>팀원 질문: {state.confirmQuestion||'-'}</p>{[['fact','확인할 사실'],['action','필요한 행동'],['support','팀장 지원'],['promise','2주 행동 약속/점검 기준']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J04-actionMap',{...form,selectedMemberId:m.id})}>실행행동 저장</button></Card>}
function Stakeholder({state,save}:any){const[form,setForm]=useState<R>({manager:'',hq:'',team:'',peer:''});return <Card><h2 className='text-xl font-bold'>이해관계자 메시지 번역</h2><Guide title='해야 할 일'>같은 실행 약속을 상사, 본사, 팀원, 동료 팀장에게 각각 다르게 설명해보세요.</Guide>{[['manager','상사/본부장'],['hq','본사 유관부서'],['team','팀원'],['peer','동료 팀장']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J05-stakeholder',{messages:form})}>메시지 저장</button></Card>}
function Review({state,save}:any){const[ai,setAi]=useState('');const[risk,setRisk]=useState('');const[finalText,setFinal]=useState('');const prompt=`우선 확인할 해석: ${state.priorityInterpretation||'-'}\n팀원 확인 질문: ${state.confirmQuestion||'-'}\n성과대화 흐름과 확인 질문을 작성해주세요.`;return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>성과대화 프롬프트</h2><Guide title='해야 할 일'>Dashboard의 해석과 확인 질문을 바탕으로 성과대화용 AI 프롬프트를 복사하세요.</Guide><pre className='preline mt-3 rounded-xl bg-slate-100 p-3'>{prompt}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>navigator.clipboard?.writeText(prompt)}>복사</button></Card><Card><h2 className='text-xl font-bold'>AI 답변 감별</h2><Field label='AI 답변' rows={5} value={ai} onChange={setAi}/><Field label='위험 문장' value={risk} onChange={setRisk}/><Field label='현장 언어 수정문' value={finalText} onChange={setFinal}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J06-review',{generatedPrompt:prompt,aiAnswer:ai,riskSentence:risk,finalText})}>감별 저장</button></Card></div>}
function CallPlan({state,save}:any){const[groups,setGroups]=useState<string[]>(state.customerGroups||[]);const[text,setText]=useState('');return <Card><h2 className='text-xl font-bold'>고객관점 콜플랜 요청</h2><Guide title='해야 할 일'>어느 고객군이 중요한지가 아니라, 방문 확대·메시지 재설계·후속조치 완료·관계 탐색 중 무엇을 우선할지 정하세요.</Guide><div className='mt-3 grid gap-2 md:grid-cols-4'>{customers.map(c=><button key={c} className={'rounded-xl border p-3 text-left '+(groups.includes(c)?'bg-cyan-50 border-cyan-700':'')} onClick={()=>setGroups(toggle(groups,c))}>{c}</button>)}</div><Field label='개선된 업무 요청문' value={text} onChange={setText}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J07-callPlan',{customerGroups:groups,finalText:text})}>콜플랜 저장</button></Card>}
function Hq({save}:any){const[brief,setBrief]=useState('캠페인 실행 요청');const[team,setTeam]=useState('');const[hq,setHq]=useState('');return <Card><h2 className='text-xl font-bold'>본사 요청 현장 번역</h2><Guide title='해야 할 일'>본사 요청을 팀원이 실행할 수 있는 현장 언어로 바꾸세요.</Guide><select className='mt-3 w-full rounded-xl border p-3' value={brief} onChange={e=>setBrief(e.target.value)}>{['캠페인 실행 요청','CRM 입력 품질 강화 요청','고객군 우선순위 조정 요청'].map(h=><option key={h}>{h}</option>)}</select><Field label='팀원 실행 요청문' value={team} onChange={setTeam}/><Field label='본사 피드백 메시지' value={hq} onChange={setHq}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J08-hq',{selectedHqBrief:brief,teamMessage:team,hqFeedback:hq})}>현장 번역 저장</button></Card>}
function OneOnOne({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({});return <Card><h2 className='text-xl font-bold'>{m.name} 1on1 코칭</h2><Guide title='해야 할 일'>확인 질문과 2주 실행 약속을 실제 1on1 대화로 바꾸세요.</Guide><p className='mt-3 rounded-xl bg-slate-50 p-3'>예상 발언: {m.comment}<br/>우선 확인할 해석: {state.priorityInterpretation||'-'}<br/>팀원 질문: {state.confirmQuestion||'-'}</p>{['대화 시작 문장','코칭 질문 5개','피해야 할 표현 3개','다음 1주 행동 약속','팀장 지원 문장'].map(f=><Field key={f} label={f} value={form[f]} onChange={(v:string)=>setForm({...form,[f]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J09-oneOnOne',{selectedMemberId:m.id,...form})}>1on1 저장</button></Card>}
function Wrap({state,save}:any){const[plan,setPlan]=useState<R>({});return <div className='grid gap-4 md:grid-cols-2'><div className='grid gap-4'><Card><h2 className='text-xl font-bold'>앞선 산출물 요약</h2><Guide title='확인할 것'>Dashboard에서 만든 해석, 질문, 2주 실행 약속이 끝까지 이어졌는지 확인하세요.</Guide><p className='mt-3'>선택 팀원: {member(state.selectedMemberId).name}</p><p>직관 판단: {state.intuitionJudgment||'-'}</p><p>우선 확인할 해석: {state.priorityInterpretation||state.causalHypothesis||'-'}</p><p>팀원 확인 질문: {state.confirmQuestion||'-'}</p><p>2주 실행 약속: {state.twoWeekCommitment||'-'}</p><p>2주 후 점검할 지표/증거: {state.recheckEvidence||'-'}</p></Card><ShareCard state={state}/></div><Card><h2 className='text-xl font-bold'>7일·30일 실행계획</h2>{['7일 실행계획','30일 점검 기준','이해관계자 조율 행동','고객 접점 품질 개선 행동','AI 활용 팀장 원칙'].map(f=><Field key={f} label={f} value={plan[f]} onChange={(v:string)=>setPlan({...plan,[f]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J10-finalPlan',{...plan,journeySummary:state,shareCard:shareCardText(state),finalText:JSON.stringify(plan)})}>최종 저장</button></Card></div>}

createRoot(document.getElementById('journey-root')!).render(<App/>);
