import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

type R = Record<string, any>;
const WEBAPP_URL = (import.meta.env.VITE_GOOGLE_SCRIPT_WEBAPP_URL || '') as string;
const CP = '본 실습은 교육용 가상 자료만 사용합니다. 실제 고객명, 제품명, 내부 수치, 민감정보는 입력하지 마세요.';

const screens = [
  ['J01','Opening','입장과 AI 안전선','교육장 입장','실습 기준 확인','안전한 질문 만들기'],
  ['J02','M1','좋은 질문 만들기','AI 안전선','질문 전환','데이터 읽기'],
  ['J03','M2','Dashboard Reading','질문 기준','데이터 신호 해석','실행행동 Map'],
  ['J04','M2','MR별 실행행동 Map','Dashboard 신호','2주 행동 약속','메시지 번역'],
  ['J05','M3','이해관계자 메시지 번역','실행행동','대상별 메시지','AI 답변 감별'],
  ['J06','M3','성과대화 AI 답변 감별','메시지 번역','AI 답변 검토','콜플랜 요청'],
  ['J07','M4','고객관점 콜플랜 요청','AI 답변 감별','실행 요청문 작성','본사 요청 번역'],
  ['J08','M4','본사 요청 현장 번역','콜플랜 요청','현장 실행안 번역','1on1 코칭'],
  ['J09','M5','MR 1on1 코칭','실행안','대화 설계','실행계획'],
  ['J10','Wrap-up','7일·30일 실행계획','모든 산출물','현업 적용 계획','강사용 공유']
].map(([id,module,title,prev,now,next])=>({id,module,title,prev,now,next}));

const metricOrder = ['콜실행률','담당처커버리지','CRM기록충실도','후속조치율','고객반응지수','성과전환지수','팀기여지수','실행지연'];
const members = [
  { id:'M01', name:'신재영 대리', type:'활동량 과다·성과전환 저조형', signal:'콜 실행률은 높지만 후속조치율과 성과전환지수가 낮다. 활동량보다 접점 목적과 후속 실행 품질 점검이 필요하다.', comment:'저는 누구보다 많이 움직이고 있습니다.', metrics:{콜실행률:112, 담당처커버리지:96, CRM기록충실도:64, 후속조치율:58, 고객반응지수:62, 성과전환지수:54, 팀기여지수:61, 실행지연:2}},
  { id:'M02', name:'이대은 대리', type:'고성과 개인플레이형', signal:'성과전환지수와 고객반응지수는 높지만 팀기여지수가 낮다. 개인성과 인정과 팀 기여 요청의 균형이 필요하다.', comment:'각자 자기 담당처는 본인이 책임지는 게 맞지 않나요?', metrics:{콜실행률:91, 담당처커버리지:88, CRM기록충실도:72, 후속조치율:74, 고객반응지수:84, 성과전환지수:128, 팀기여지수:42, 실행지연:1}},
  { id:'M03', name:'박재욱 사원', type:'신입 위축형', signal:'CRM 기록은 성실하지만 콜 실행률과 고객반응지수가 낮다. 신입 위축과 접점 전 준비 부족 가능성을 확인해야 한다.', comment:'제가 가면 오히려 불편해하시는 것 같습니다.', metrics:{콜실행률:72, 담당처커버리지:69, CRM기록충실도:90, 후속조치율:67, 고객반응지수:51, 성과전환지수:48, 팀기여지수:70, 실행지연:1}},
  { id:'M04', name:'유희관 과장', type:'경력 안정형', signal:'담당처 관계와 고객반응은 안정적이나 CRM 기록과 캠페인 실행이 낮다. 변화 요구를 현장 언어로 연결해야 한다.', comment:'현장에서는 그런 방식이 잘 안 맞습니다.', metrics:{콜실행률:86, 담당처커버리지:92, CRM기록충실도:55, 후속조치율:63, 고객반응지수:76, 성과전환지수:82, 팀기여지수:58, 실행지연:3}},
  { id:'M05', name:'김문호 차장', type:'방어적 목표미달형', signal:'목표진척과 실행 속도가 모두 낮다. 외부 요인 탓으로 단정하거나 반박하기보다 데이터 기반 공동 진단이 필요하다.', comment:'이번 지역 상황은 제가 어떻게 할 수 있는 게 아닙니다.', metrics:{콜실행률:79, 담당처커버리지:75, CRM기록충실도:68, 후속조치율:61, 고객반응지수:60, 성과전환지수:68, 팀기여지수:55, 실행지연:5}},
  { id:'M06', name:'김재호 차장', type:'실행지연·CRM 부실형', signal:'콜 실행은 유지되지만 CRM 기록과 후속조치율이 낮다. 완료 기준과 사후보고 기준 명확화가 필요하다.', comment:'현장 대응하느라 입력은 나중에 하게 됩니다.', metrics:{콜실행률:93, 담당처커버리지:81, CRM기록충실도:41, 후속조치율:45, 고객반응지수:69, 성과전환지수:73, 팀기여지수:62, 실행지연:4}}
];
const customers = [
  { id:'CG-A', label:'고객군 A', criteria:'접점 낮음 · 반응 높음 · 성장 가능성 높음', meaning:'접점 기회는 부족하지만 반응과 성장 가능성이 높은 고객군입니다.', decision:'후속조치와 접점 확대를 우선 검토하되, 무작정 방문 횟수를 늘리기보다 접점 목적과 다음 행동을 분명히 합니다.', question:'반응이 좋은데도 후속조치나 다음 접점이 끊기는 이유는 무엇인가?' },
  { id:'CG-B', label:'고객군 B', criteria:'접점 높음 · 반응 낮음 · 성장 가능성 낮음', meaning:'방문은 많지만 고객 반응이 낮아 활동량 대비 접점 효과가 약한 고객군입니다.', decision:'방문 횟수를 더 늘리기보다 메시지 적합성, 접점 목적, 고객 니즈 해석을 재설계합니다.', question:'많이 방문했는데 반응이 낮다면 문제는 횟수인가, 메시지인가?' },
  { id:'CG-C', label:'고객군 C', criteria:'후속조치 필요 높음 · 신뢰 리스크 높음', meaning:'후속조치가 늦어지면 신뢰가 떨어질 가능성이 높은 고객군입니다.', decision:'새로운 방문보다 약속 이행, 자료 제공, 다음 접점 일정, 기록 품질을 우선 관리합니다.', question:'고객 신뢰를 지키기 위해 이번 주 반드시 완료해야 할 후속조치는 무엇인가?' },
  { id:'CG-D', label:'고객군 D', criteria:'접점 낮음 · 반응 보통 · 성장 가능성 높음', meaning:'아직 접점은 낮지만 향후 성장 가능성이 있는 탐색 고객군입니다.', decision:'큰 자원을 바로 투입하기보다 작은 접점, 관계 탐색, 정보 적합성 확인부터 시작합니다.', question:'지금은 관찰할 단계인가, 작은 접점을 만들어볼 단계인가?' }
];
const gaps = ['접점 목적 불명확','후속조치 미흡','고객군 우선순위 문제','메시지 일관성 부족','동기 저하','팀장 지원 필요'];
const criteria = ['보안성','CP 준수성','고객가치성','현장성','성과책임','실행가능성','팀장 역할','표현 안전성'];
const hqBriefs = ['캠페인 실행 요청','CRM 입력 품질 강화 요청','고객군 우선순위 조정 요청'];
const metricDefs:R = {
  콜실행률: { base:'100 = 팀/지역 목표 콜 실행 기준', high:'높을수록 활동량이 많음', low:'낮을수록 계획 대비 접점 부족 가능성', note:'계획된 콜 활동이 얼마나 실행되었는지를 보는 활동량 지표입니다. 높다고 반드시 성과가 좋은 것은 아니며 접점 목적과 품질을 함께 봐야 합니다.' },
  담당처커버리지: { base:'100 = 담당처 커버리지 목표 기준', high:'높을수록 담당처 접점 범위가 넓음', low:'낮을수록 특정 담당처 편중 또는 미접촉 가능성', note:'담당해야 할 고객군 또는 담당처를 얼마나 균형 있게 커버했는지 보는 범위 지표입니다.' },
  CRM기록충실도: { base:'100 = 요구 기록 품질 기준', high:'높을수록 CRM 기록이 구체적임', low:'낮을수록 후속조치 누락·공유 단절 가능성', note:'콜 목적, 고객 반응, 후속조치, 다음 접점 계획이 충실히 기록되었는지 보는 지표입니다.' },
  후속조치율: { base:'100 = 후속조치 목표 이행 기준', high:'높을수록 약속·자료·재접점 실행이 좋음', low:'낮을수록 접점 후 관리 공백 가능성', note:'콜 이후 필요한 후속조치가 제때 이루어졌는지 보는 실행 품질 지표입니다.' },
  고객반응지수: { base:'100 = 평균적 고객 반응 기준', high:'높을수록 고객 반응이 긍정적임', low:'낮을수록 메시지 적합성·관계·접점 목적 재점검 필요', note:'고객의 관심, 대화 참여도, 후속 논의 가능성을 가상 지수화한 지표입니다.' },
  성과전환지수: { base:'100 = 목표 대비 평균 성과전환 기준', high:'높을수록 활동이 성과로 연결됨', low:'낮을수록 활동량 대비 결과 전환이 약함', note:'활동이 실제 성과 신호로 얼마나 연결되는지 보는 결과 연결 지표입니다.' },
  팀기여지수: { base:'100 = 기대되는 팀 기여 기준', high:'높을수록 노하우 공유·협업 기여가 큼', low:'낮을수록 개인성과 중심 가능성', note:'개인 실적 외에 팀 학습, 공유, 협업에 기여하는 정도를 보는 지표입니다.' },
  실행지연: { base:'숫자가 낮을수록 좋음', high:'높을수록 약속·보고·후속 실행 지연이 많음', low:'낮을수록 실행 리듬이 안정적임', note:'다른 지수와 달리 100 기준 지수가 아니라 지연 건수에 가까운 위험 신호입니다.' }
};
function metricLevel(k:string,v:any){ if(k==='실행지연') return Number(v)>=4?'주의':Number(v)>=2?'관찰':'양호'; if(Number(v)>=110) return '강점'; if(Number(v)>=90) return '기준권'; if(Number(v)>=70) return '관찰'; return '주의'; }

const uid=(p:string)=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const now=()=>new Date().toISOString();
function getJson<T>(k:string,i:T):T{try{return JSON.parse(localStorage.getItem(k)||'null')??i}catch{return i}}
function setJson(k:string,v:any){localStorage.setItem(k,JSON.stringify(v))}
function useStore<T>(k:string,i:T){const[v,s]=useState<T>(()=>getJson(k,i));useEffect(()=>setJson(k,v),[k,v]);return[v,s] as const}
function Card({children,className=''}:any){return <div className={'rounded-2xl border bg-white p-5 shadow-sm '+className}>{children}</div>}
function Field({label,value,onChange,rows=3}:any){return <label className='block'><b className='text-sm'>{label}</b><textarea className='mt-1 w-full rounded-xl border p-3' rows={rows} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function copyText(t:string){navigator.clipboard?.writeText(t)}
function member(id:string){return members.find(m=>m.id===id)||members[0]}
async function callGoogle(action:string,payload:R={}){if(!WEBAPP_URL)throw new Error('no url');const r=await fetch(WEBAPP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'failed');return j.data}
function payload(p:R,screen:R,key:string,out:R){return{responseId:uid('RJ'),participantId:p.participantId,sessionCode:p.sessionCode,teamName:p.teamName,moduleId:screen.module,screenId:screen.id,activityId:key,activityName:screen.title,inputData:{},outputData:out,promptText:out.generatedPrompt||'',aiAnswerText:out.aiAnswer||'',reviewData:out.reviewChecks||{},finalText:out.finalText||JSON.stringify(out),isCompleted:true,createdAt:now(),updatedAt:now()}}

function App(){const[step,setStep]=useStore('c1bio_flow_step',0);const[participant,setParticipant]=useStore<R>('c1bio_flow_participant',{participantId:uid('PJ'),sessionCode:'C1BIO-1차',name:'',teamName:''});const[state,setState]=useStore<R>('c1bio_flow_state',{selectedMemberId:'M01',responses:{}});const[status,setStatus]=useState('localStorage 저장됨');const screen=screens[step];async function save(key:string,patch:R){const next={...state,...patch,responses:{...(state.responses||{}),[key]:patch}};setState(next);if(WEBAPP_URL){try{await callGoogle('saveResponse',payload(participant,screen,key,patch));setStatus('Google Sheets 저장됨')}catch{setStatus('Google 저장 실패 · localStorage 유지')}}}async function next(){if(WEBAPP_URL){try{await callGoogle('saveParticipant',{...participant,role:'participant',createdAt:participant.createdAt||now(),updatedAt:now(),userAgent:navigator.userAgent})}catch{}}setStep(Math.min(screens.length-1,step+1))}return <div className='mx-auto max-w-7xl p-5'><header className='mb-5 flex justify-between gap-3'><div><h1 className='text-2xl font-bold'>C1바이오 Full Flow Journey</h1><p className='text-slate-600'>{screen.module} · {screen.title} · {Math.round((step+1)/screens.length*100)}%</p></div><div className='flex gap-2'><button className='rounded-xl border px-4 py-2' onClick={()=>location.href='/'}>기존 MVP</button><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>location.href='/instructor-live.html'}>Live Dashboard</button></div></header><div className='safe mb-4 rounded-xl px-4 py-3 text-sm font-medium'>{CP}</div><Card><div className='grid gap-3 md:grid-cols-3'><div><b>이전 산출물</b><p>{screen.prev}</p></div><div><b>현재 실습</b><p className='text-cyan-700'>{screen.now}</p></div><div><b>다음 연결</b><p>{screen.next}</p></div></div></Card><div className='my-4 h-2 rounded-full bg-slate-200'><div className='h-2 rounded-full bg-cyan-700' style={{width:((step+1)/screens.length*100)+'%'}}/></div><Screen step={step} participant={participant} setParticipant={setParticipant} state={state} save={save}/><footer className='sticky bottom-0 mt-6 flex justify-between rounded-2xl border bg-white/90 p-3'><button className='rounded-xl border px-5 py-3' onClick={()=>setStep(Math.max(0,step-1))}>이전</button><span className='py-3 text-sm'>{status}</span><button className='rounded-xl bg-cyan-700 px-5 py-3 text-white' onClick={next}>저장하고 다음</button></footer></div>}
function Screen({step,participant,setParticipant,state,save}:any){const common={state,save};return [<Entry participant={participant} setParticipant={setParticipant} save={save}/>,<PromptLab {...common}/>,<Dashboard {...common}/>,<ActionMap {...common}/>,<Stakeholder {...common}/>,<Review {...common}/>,<CallPlan {...common}/>,<Hq {...common}/>,<OneOnOne {...common}/>,<Wrap state={state} save={save}/>][step]}
function Entry({participant,setParticipant,save}:any){return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>입장</h2><div className='mt-4 grid gap-3 md:grid-cols-3'>{[['sessionCode','세션코드'],['name','이름'],['teamName','팀명']].map(([k,l])=><label key={k}><b>{l}</b><input className='mt-1 w-full rounded-xl border p-3' value={participant[k]} onChange={e=>setParticipant({...participant,[k]:e.target.value})}/></label>)}</div></Card><Card><h3 className='font-bold'>AI 안전선 확인</h3><p className='mt-2 text-slate-600'>{CP}</p><button className='mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J01-entry',{consentChecked:true,finalText:'AI 안전선 확인'})}>확인 저장</button></Card></div>}
function PromptLab({save}:any){const[prompt,setPrompt]=useState('역할: 당신은 영업팀장의 업무관리 코치입니다.\n상황: 교육용 가상 데이터입니다.\n요청: 모호한 업무 지시를 고객 신뢰, 접점 품질, 후속조치 기준이 포함된 실행 요청문으로 바꿔주세요.');return <Card><h2 className='text-xl font-bold'>좋은 질문 만들기</h2><p className='rounded-xl bg-orange-50 p-3'>나쁜 질문: 고객관리 더 신경 쓰라고 말하고 싶은데 어떻게 하죠?</p><Field label='안전한 프롬프트' rows={8} value={prompt} onChange={setPrompt}/><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>{copyText(prompt);save('J02-prompt',{generatedPrompt:prompt,nextAction:'데이터 읽기에 적용'})}}>복사 및 저장</button></Card>}
function Dashboard({state,save}:any){const[id,setId]=useState(state.selectedMemberId||'M01');const m=member(id);const[selGaps,setGaps]=useState<string[]>(state.gapHypotheses||[]);const[q,setQ]=useState(state.confirmationQuestion||'');return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>Dashboard Reading</h2><div className='mb-3 rounded-xl bg-cyan-50 p-3 text-sm'><b>지표 해석 기준</b><br/>대부분의 지표는 <b>100을 팀/지역 목표 또는 평균 기준선</b>으로 둔 교육용 Index입니다. 100보다 높으면 기준 대비 양호, 100보다 낮으면 확인이 필요한 신호입니다. 단, <b>실행지연</b>은 지수가 아니라 건수형 위험 신호로 숫자가 낮을수록 좋습니다.</div><select className='mt-2 w-full rounded-xl border p-3' value={id} onChange={e=>setId(e.target.value)}>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.type}</option>)}</select><div className='mt-3 grid grid-cols-1 gap-2 md:grid-cols-4'>{metricOrder.map(k=>{const v=m.metrics[k]; return <div key={k} className='rounded-xl bg-slate-50 p-3'><div className='flex items-start justify-between gap-2'><p className='text-xs font-semibold'>{k}</p><span className='rounded-full bg-white px-2 py-1 text-[11px]'>{metricLevel(k,v)}</span></div><b className='text-xl'>{String(v)}</b><p className='mt-1 text-[11px] text-slate-500'>{metricDefs[k]?.base}</p><p className='mt-2 text-xs text-slate-600'>{metricDefs[k]?.note}</p></div>})}</div><p className='mt-3 rounded-xl bg-slate-50 p-3'>{m.signal}</p></Card><Card><h3 className='font-bold'>주요 지표 설명</h3><div className='mt-3 grid gap-2 md:grid-cols-2'>{metricOrder.map(k=>{const d=metricDefs[k]; return <div key={k} className='rounded-xl border p-3 text-sm'><b>{k}</b><p className='text-slate-600'>{d.high}</p><p className='text-slate-600'>{d.low}</p></div>})}</div></Card><Card><h3 className='font-bold'>고객군 분류 기준과 의사결정 영향</h3><p className='mt-2 rounded-xl bg-cyan-50 p-3 text-sm'>고객군 A~D는 실제 고객 등급이 아니라 교육용 가상 분류입니다. 기준은 <b>접점 빈도, 고객 반응, 후속조치 필요도, 성장 가능성</b>입니다. 이 분류는 고객을 평가하기 위한 것이 아니라, 팀장의 콜플랜 우선순위와 코칭 질문을 정교화하기 위한 판단 도구입니다.</p><div className='mt-3 grid gap-3 md:grid-cols-2'>{customers.map(c=><div key={c.id} className='rounded-xl border p-3 text-sm'><b>{c.label}</b><p className='mt-1 text-xs text-cyan-800'>{c.criteria}</p><p className='mt-2 text-slate-700'>{c.meaning}</p><p className='mt-2'><b>팀장 판단:</b> {c.decision}</p><p className='mt-2'><b>코칭 질문:</b> {c.question}</p></div>)}</div></Card><Card><h3 className='font-bold'>Gap 가설</h3><div className='mt-2 flex flex-wrap gap-2'>{gaps.map(g=><button key={g} className={'rounded-xl border px-3 py-2 '+(selGaps.includes(g)?'bg-cyan-700 text-white':'')} onClick={()=>setGaps(selGaps.includes(g)?selGaps.filter(x=>x!==g):[...selGaps,g])}>{g}</button>)}</div><Field label='확인 질문' value={q} onChange={setQ}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J03-dashboard',{selectedMemberId:id,gapHypotheses:selGaps,confirmationQuestion:q,dataSignal:m.signal})}>Dashboard 판단 저장</button></Card></div>}
function ActionMap({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({fact:state.dataSignal||m.signal,action:'',support:'',promise:''});return <Card><h2 className='text-xl font-bold'>{m.name} 실행행동 Map</h2><p className='rounded-xl bg-slate-50 p-3'>연결된 Gap: {(state.gapHypotheses||[]).join(', ')}</p>{[['fact','확인할 사실'],['action','필요한 행동'],['support','팀장 지원'],['promise','2주 행동 약속']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J04-actionMap',{...form,selectedMemberId:m.id})}>실행행동 저장</button></Card>}
function Stakeholder({state,save}:any){const[form,setForm]=useState<R>({manager:'',hq:'',team:'',peer:''});return <Card><h2 className='text-xl font-bold'>이해관계자 메시지 번역</h2>{[['manager','상사/본부장'],['hq','본사 유관부서'],['team','팀원'],['peer','동료 팀장']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J05-stakeholder',{messages:form})}>메시지 저장</button></Card>}
function Review({state,save}:any){const m=member(state.selectedMemberId);const[ai,setAi]=useState('');const[checks,setChecks]=useState<string[]>([]);const[risk,setRisk]=useState('');const[finalText,setFinal]=useState('');const prompt=`대상: ${m.name}\n신호: ${m.signal}\nGap: ${(state.gapHypotheses||[]).join(', ')}\n성과대화 흐름을 작성해주세요.`;return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>성과대화 프롬프트</h2><pre className='preline rounded-xl bg-slate-100 p-3'>{prompt}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>copyText(prompt)}>복사</button></Card><Card><h2 className='text-xl font-bold'>AI 답변 감별</h2><Field label='AI 답변' rows={5} value={ai} onChange={setAi}/><div className='flex flex-wrap gap-2'>{criteria.map(c=><button key={c} className={'rounded-xl border px-3 py-2 '+(checks.includes(c)?'bg-cyan-700 text-white':'')} onClick={()=>setChecks(checks.includes(c)?checks.filter(x=>x!==c):[...checks,c])}>{c}</button>)}</div><Field label='위험 문장' value={risk} onChange={setRisk}/><Field label='현장 언어 수정문' value={finalText} onChange={setFinal}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J06-review',{generatedPrompt:prompt,aiAnswer:ai,reviewChecks:checks,riskSentence:risk,finalText})}>감별 저장</button></Card></div>}
function CallPlan({state,save}:any){const[groups,setGroups]=useState<string[]>(state.customerGroups||[]);const[text,setText]=useState('');return <Card><h2 className='text-xl font-bold'>고객관점 콜플랜 요청</h2><p className='mb-3 rounded-xl bg-cyan-50 p-3 text-sm'>고객군 선택은 “어느 고객이 더 중요한가”가 아니라 <b>방문 확대, 메시지 재설계, 후속조치 완료, 관계 탐색 중 무엇을 우선할 것인가</b>를 정하기 위한 의사결정입니다.</p><div className='grid gap-2 md:grid-cols-4'>{customers.map(c=><button key={c.id} className={'rounded-xl border p-3 text-left '+(groups.includes(c.label)?'bg-cyan-50 border-cyan-700':'')} onClick={()=>setGroups(groups.includes(c.label)?groups.filter(x=>x!==c.label):[...groups,c.label])}><b>{c.label}</b><p className='text-xs text-cyan-800'>{c.criteria}</p><p className='mt-2 text-sm'>{c.decision}</p></button>)}</div><Field label='개선된 업무 요청문' value={text} onChange={setText}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J07-callPlan',{customerGroups:groups,finalText:text})}>콜플랜 저장</button></Card>}
function Hq({save}:any){const[brief,setBrief]=useState(hqBriefs[0]);const[team,setTeam]=useState('');const[hq,setHq]=useState('');return <Card><h2 className='text-xl font-bold'>본사 요청 현장 번역</h2><select className='mt-2 w-full rounded-xl border p-3' value={brief} onChange={e=>setBrief(e.target.value)}>{hqBriefs.map(h=><option key={h}>{h}</option>)}</select><Field label='팀원 실행 요청문' value={team} onChange={setTeam}/><Field label='본사 피드백 메시지' value={hq} onChange={setHq}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J08-hq',{selectedHqBrief:brief,teamMessage:team,hqFeedback:hq})}>현장 번역 저장</button></Card>}
function OneOnOne({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({});return <Card><h2 className='text-xl font-bold'>{m.name} 1on1 코칭</h2><p className='rounded-xl bg-slate-50 p-3'>예상 발언: {m.comment}<br/>위험 문장: {state.riskSentence||'-'}</p>{['대화 시작 문장','코칭 질문 5개','피해야 할 표현 3개','다음 1주 행동 약속','팀장 지원 문장'].map(f=><Field key={f} label={f} value={form[f]} onChange={(v:string)=>setForm({...form,[f]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J09-oneOnOne',{selectedMemberId:m.id,...form})}>1on1 저장</button></Card>}
function Wrap({state,save}:any){const[plan,setPlan]=useState<R>({});const summary=JSON.stringify(state,null,2);return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>앞선 산출물 요약</h2><p>선택 팀원: {member(state.selectedMemberId).name}</p><p>Gap: {(state.gapHypotheses||[]).join(', ')}</p><p>고객군: {(state.customerGroups||[]).join(', ')}</p><pre className='preline mt-3 max-h-72 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{summary}</pre></Card><Card><h2 className='text-xl font-bold'>7일·30일 실행계획</h2>{['7일 실행계획','30일 점검 기준','이해관계자 조율 행동','고객 접점 품질 개선 행동','AI 활용 팀장 원칙'].map(f=><Field key={f} label={f} value={plan[f]} onChange={(v:string)=>setPlan({...plan,[f]:v})}/>) }<button className='mr-2 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>copyText(JSON.stringify({summary:state,plan},null,2))}>전체 결과 복사</button><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J10-finalPlan',{...plan,journeySummary:state,finalText:JSON.stringify(plan)})}>최종 저장</button></Card></div>}

createRoot(document.getElementById('journey-root')!).render(<App/>);
