import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

type R = Record<string, any>;
const WEBAPP_URL = (import.meta.env.VITE_GOOGLE_SCRIPT_WEBAPP_URL || '') as string;
const CP = '본 실습은 교육용 가상 자료만 사용합니다. 실제 고객명, 제품명, 내부 수치, 민감정보는 입력하지 마세요.';

const screens = [
  ['J01','Opening','입장과 AI 안전선','교육장 입장','실습 기준 확인','안전한 질문 만들기'],
  ['J02','M1','좋은 질문 만들기','AI 안전선','질문 전환','데이터 읽기'],
  ['J03','M2','Dashboard Reading','질문 기준','데이터 신호 해석','실행행동 Map'],
  ['J04','M2','MR별 실행행동 Map','Dashboard 신호','2주 행동 약속','메시지 번역'],
  ['J05','M3','이해관계자 메시지 번역','실행행동','대상별 메시지','AI 답변 감별'],
  ['J06','M3','성과대화 AI 답변 감별','메시지 번역','AI 답변 검토','콜플랜 요청'],
  ['J07','M4','고객관점 콜플랜 요청','AI 답변 감별','실행 요청문 작성','본사 요청 번역'],
  ['J08','M4','본사 요청 현장 번역','콜플랜 요청','현장 실행안 번역','1on1 코칭'],
  ['J09','M5','MR 1on1 코칭','실행안','대화 설계','실행계획'],
  ['J10','Wrap-up','7일·30일 실행계획','모든 산출물','현업 적용 계획','강사용 공유']
].map(([id,module,title,prev,now,next])=>({id,module,title,prev,now,next}));

const members = [
  { id:'M01', name:'신재영 대리', type:'활동량 과다·성과전환 저조형', signal:'활동량은 높지만 후속조치와 성과전환이 낮다.', comment:'저는 누구보다 많이 움직이고 있습니다.', metrics:{콜실행률:112, 후속조치율:58, 성과전환지수:54, 고객반응지수:62}},
  { id:'M02', name:'이대은 대리', type:'고성과 개인플레이형', signal:'성과전환은 높지만 팀 기여가 낮다.', comment:'각자 자기 담당처는 본인이 책임지는 게 맞지 않나요?', metrics:{콜실행률:91, 성과전환지수:128, 팀기여지수:42, 고객반응지수:84}},
  { id:'M03', name:'박재욱 사원', type:'신입 위축형', signal:'기록은 성실하지만 접점 자신감과 고객 반응이 낮다.', comment:'제가 가면 오히려 불편해하시는 것 같습니다.', metrics:{콜실행률:72, 기록충실도:90, 고객반응지수:51, 성과전환지수:48}},
  { id:'M04', name:'유희관 과장', type:'경력 안정형', signal:'관계는 안정적이나 변화 실행과 기록 품질이 낮다.', comment:'현장에서는 그런 방식이 잘 안 맞습니다.', metrics:{콜실행률:86, 기록충실도:55, 고객반응지수:76, 성과전환지수:82}},
  { id:'M05', name:'김문호 차장', type:'방어적 목표미달형', signal:'목표진척과 실행 속도가 모두 낮고 외부 요인 설명이 많다.', comment:'이번 지역 상황은 제가 어떻게 할 수 있는 게 아닙니다.', metrics:{콜실행률:79, 후속조치율:61, 고객반응지수:60, 성과전환지수:68, 실행지연:5}},
  { id:'M06', name:'김재호 차장', type:'실행지연·CRM 부실형', signal:'콜 실행은 유지되지만 기록 품질과 후속조치율이 낮다.', comment:'현장 대응하느라 입력은 나중에 하게 됩니다.', metrics:{콜실행률:93, 기록충실도:41, 후속조치율:45, 고객반응지수:69, 실행지연:4}}
];
const customers = ['고객군 A: 접점은 낮지만 반응과 성장 가능성이 높음','고객군 B: 접점은 높지만 반응이 낮아 목적 재설계 필요','고객군 C: 후속조치 지연 시 신뢰 리스크 높음','고객군 D: 접점은 낮지만 성장 가능성 있음'];
const gaps = ['접점 목적 불명확','후속조치 미흡','고객군 우선순위 문제','메시지 일관성 부족','동기 저하','팀장 지원 필요'];
const criteria = ['보안성','CP 준수성','고객가치성','현장성','성과책임','실행가능성','팀장 역할','표현 안전성'];
const hqBriefs = ['캠페인 실행 요청','CRM 입력 품질 강화 요청','고객군 우선순위 조정 요청'];

const uid=(p:string)=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const now=()=>new Date().toISOString();
function getJson<T>(k:string,i:T):T{try{return JSON.parse(localStorage.getItem(k)||'null')??i}catch{return i}}
function setJson(k:string,v:any){localStorage.setItem(k,JSON.stringify(v))}
function useStore<T>(k:string,i:T){const[v,s]=useState<T>(()=>getJson(k,i));useEffect(()=>setJson(k,v),[k,v]);return[v,s] as const}
function Card({children,className=''}:any){return <div className={'rounded-2xl border bg-white p-5 shadow-sm '+className}>{children}</div>}
function Field({label,value,onChange,rows=3}:any){return <label className='block'><b className='text-sm'>{label}</b><textarea className='mt-1 w-full rounded-xl border p-3' rows={rows} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function copyText(t:string){navigator.clipboard?.writeText(t)}
function member(id:string){return members.find(m=>m.id===id)||members[0]}
async function callGoogle(action:string,payload:R={}){if(!WEBAPP_URL)throw new Error('no url');const r=await fetch(WEBAPP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'failed');return j.data}
function payload(p:R,screen:R,key:string,out:R){return{responseId:uid('RJ'),participantId:p.participantId,sessionCode:p.sessionCode,teamName:p.teamName,moduleId:screen.module,screenId:screen.id,activityId:key,activityName:screen.title,inputData:{},outputData:out,promptText:out.generatedPrompt||'',aiAnswerText:out.aiAnswer||'',reviewData:out.reviewChecks||{},finalText:out.finalText||JSON.stringify(out),isCompleted:true,createdAt:now(),updatedAt:now()}}

function App(){const[step,setStep]=useStore('c1bio_flow_step',0);const[participant,setParticipant]=useStore<R>('c1bio_flow_participant',{participantId:uid('PJ'),sessionCode:'C1BIO-1차',name:'',teamName:''});const[state,setState]=useStore<R>('c1bio_flow_state',{selectedMemberId:'M01',responses:{}});const[status,setStatus]=useState('localStorage 저장됨');const screen=screens[step];async function save(key:string,patch:R){const next={...state,...patch,responses:{...(state.responses||{}),[key]:patch}};setState(next);if(WEBAPP_URL){try{await callGoogle('saveResponse',payload(participant,screen,key,patch));setStatus('Google Sheets 저장됨')}catch{setStatus('Google 저장 실패 · localStorage 유지')}}}async function next(){if(WEBAPP_URL){try{await callGoogle('saveParticipant',{...participant,role:'participant',createdAt:participant.createdAt||now(),updatedAt:now(),userAgent:navigator.userAgent})}catch{}}setStep(Math.min(screens.length-1,step+1))}return <div className='mx-auto max-w-7xl p-5'><header className='mb-5 flex justify-between gap-3'><div><h1 className='text-2xl font-bold'>C1바이오 Full Flow Journey</h1><p className='text-slate-600'>{screen.module} · {screen.title} · {Math.round((step+1)/screens.length*100)}%</p></div><div className='flex gap-2'><button className='rounded-xl border px-4 py-2' onClick={()=>location.href='/'}>기존 MVP</button><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>location.href='/instructor-live.html'}>Live Dashboard</button></div></header><div className='safe mb-4 rounded-xl px-4 py-3 text-sm font-medium'>{CP}</div><Card><div className='grid gap-3 md:grid-cols-3'><div><b>이전 산출물</b><p>{screen.prev}</p></div><div><b>현재 실습</b><p className='text-cyan-700'>{screen.now}</p></div><div><b>다음 연결</b><p>{screen.next}</p></div></div></Card><div className='my-4 h-2 rounded-full bg-slate-200'><div className='h-2 rounded-full bg-cyan-700' style={{width:((step+1)/screens.length*100)+'%'}}/></div><Screen step={step} participant={participant} setParticipant={setParticipant} state={state} save={save}/><footer className='sticky bottom-0 mt-6 flex justify-between rounded-2xl border bg-white/90 p-3'><button className='rounded-xl border px-5 py-3' onClick={()=>setStep(Math.max(0,step-1))}>이전</button><span className='py-3 text-sm'>{status}</span><button className='rounded-xl bg-cyan-700 px-5 py-3 text-white' onClick={next}>저장하고 다음</button></footer></div>}
function Screen({step,participant,setParticipant,state,save}:any){const common={state,save};return [<Entry participant={participant} setParticipant={setParticipant} save={save}/>,<PromptLab {...common}/>,<Dashboard {...common}/>,<ActionMap {...common}/>,<Stakeholder {...common}/>,<Review {...common}/>,<CallPlan {...common}/>,<Hq {...common}/>,<OneOnOne {...common}/>,<Wrap state={state} save={save}/>][step]}
function Entry({participant,setParticipant,save}:any){return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>입장</h2><div className='mt-4 grid gap-3 md:grid-cols-3'>{[['sessionCode','세션코드'],['name','이름'],['teamName','팀명']].map(([k,l])=><label key={k}><b>{l}</b><input className='mt-1 w-full rounded-xl border p-3' value={participant[k]} onChange={e=>setParticipant({...participant,[k]:e.target.value})}/></label>)}</div></Card><Card><h3 className='font-bold'>AI 안전선 확인</h3><p className='mt-2 text-slate-600'>{CP}</p><button className='mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J01-entry',{consentChecked:true,finalText:'AI 안전선 확인'})}>확인 저장</button></Card></div>}
function PromptLab({save}:any){const[prompt,setPrompt]=useState('역할: 당신은 영업팀장의 업무관리 코치입니다.\n상황: 교육용 가상 데이터입니다.\n요청: 모호한 업무 지시를 고객 신뢰, 접점 품질, 후속조치 기준이 포함된 실행 요청문으로 바꿔주세요.');return <Card><h2 className='text-xl font-bold'>좋은 질문 만들기</h2><p className='rounded-xl bg-orange-50 p-3'>나쁜 질문: 고객관리 더 신경 쓰라고 말하고 싶은데 어떻게 하죠?</p><Field label='안전한 프롬프트' rows={8} value={prompt} onChange={setPrompt}/><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>{copyText(prompt);save('J02-prompt',{generatedPrompt:prompt,nextAction:'데이터 읽기에 적용'})}}>복사 및 저장</button></Card>}
function Dashboard({state,save}:any){const[id,setId]=useState(state.selectedMemberId||'M01');const m=member(id);const[selGaps,setGaps]=useState<string[]>(state.gapHypotheses||[]);const[q,setQ]=useState(state.confirmationQuestion||'');return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>Dashboard Reading</h2><select className='mt-2 w-full rounded-xl border p-3' value={id} onChange={e=>setId(e.target.value)}>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.type}</option>)}</select><div className='mt-3 grid grid-cols-2 gap-2 md:grid-cols-4'>{Object.entries(m.metrics).map(([k,v])=><div key={k} className='rounded-xl bg-slate-50 p-3'><p className='text-xs'>{k}</p><b>{String(v)}</b></div>)}</div><p className='mt-3 rounded-xl bg-slate-50 p-3'>{m.signal}</p></Card><div className='grid gap-3 md:grid-cols-4'>{customers.map(c=><Card key={c}><p className='text-sm'>{c}</p></Card>)}</div><Card><h3 className='font-bold'>Gap 가설</h3><div className='mt-2 flex flex-wrap gap-2'>{gaps.map(g=><button key={g} className={'rounded-xl border px-3 py-2 '+(selGaps.includes(g)?'bg-cyan-700 text-white':'')} onClick={()=>setGaps(selGaps.includes(g)?selGaps.filter(x=>x!==g):[...selGaps,g])}>{g}</button>)}</div><Field label='확인 질문' value={q} onChange={setQ}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J03-dashboard',{selectedMemberId:id,gapHypotheses:selGaps,confirmationQuestion:q,dataSignal:m.signal})}>Dashboard 판단 저장</button></Card></div>}
function ActionMap({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({fact:state.dataSignal||m.signal,action:'',support:'',promise:''});return <Card><h2 className='text-xl font-bold'>{m.name} 실행행동 Map</h2><p className='rounded-xl bg-slate-50 p-3'>연결된 Gap: {(state.gapHypotheses||[]).join(', ')}</p>{[['fact','확인할 사실'],['action','필요한 행동'],['support','팀장 지원'],['promise','2주 행동 약속']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J04-actionMap',{...form,selectedMemberId:m.id})}>실행행동 저장</button></Card>}
function Stakeholder({state,save}:any){const[form,setForm]=useState<R>({manager:'',hq:'',team:'',peer:''});return <Card><h2 className='text-xl font-bold'>이해관계자 메시지 번역</h2>{[['manager','상사/본부장'],['hq','본사 유관부서'],['team','팀원'],['peer','동료 팀장']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={(v:string)=>setForm({...form,[k]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J05-stakeholder',{messages:form})}>메시지 저장</button></Card>}
function Review({state,save}:any){const m=member(state.selectedMemberId);const[ai,setAi]=useState('');const[checks,setChecks]=useState<string[]>([]);const[risk,setRisk]=useState('');const[finalText,setFinal]=useState('');const prompt=`대상: ${m.name}\n신호: ${m.signal}\nGap: ${(state.gapHypotheses||[]).join(', ')}\n성과대화 흐름을 작성해주세요.`;return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>성과대화 프롬프트</h2><pre className='preline rounded-xl bg-slate-100 p-3'>{prompt}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>copyText(prompt)}>복사</button></Card><Card><h2 className='text-xl font-bold'>AI 답변 감별</h2><Field label='AI 답변' rows={5} value={ai} onChange={setAi}/><div className='flex flex-wrap gap-2'>{criteria.map(c=><button key={c} className={'rounded-xl border px-3 py-2 '+(checks.includes(c)?'bg-cyan-700 text-white':'')} onClick={()=>setChecks(checks.includes(c)?checks.filter(x=>x!==c):[...checks,c])}>{c}</button>)}</div><Field label='위험 문장' value={risk} onChange={setRisk}/><Field label='현장 언어 수정문' value={finalText} onChange={setFinal}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J06-review',{generatedPrompt:prompt,aiAnswer:ai,reviewChecks:checks,riskSentence:risk,finalText})}>감별 저장</button></Card></div>}
function CallPlan({state,save}:any){const[groups,setGroups]=useState<string[]>(state.customerGroups||[]);const[text,setText]=useState('');return <Card><h2 className='text-xl font-bold'>고객관점 콜플랜 요청</h2><div className='grid gap-2 md:grid-cols-4'>{customers.map(c=><button key={c} className={'rounded-xl border p-3 text-left '+(groups.includes(c)?'bg-cyan-50 border-cyan-700':'')} onClick={()=>setGroups(groups.includes(c)?groups.filter(x=>x!==c):[...groups,c])}>{c}</button>)}</div><Field label='개선된 업무 요청문' value={text} onChange={setText}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J07-callPlan',{customerGroups:groups,finalText:text})}>콜플랜 저장</button></Card>}
function Hq({save}:any){const[brief,setBrief]=useState(hqBriefs[0]);const[team,setTeam]=useState('');const[hq,setHq]=useState('');return <Card><h2 className='text-xl font-bold'>본사 요청 현장 번역</h2><select className='mt-2 w-full rounded-xl border p-3' value={brief} onChange={e=>setBrief(e.target.value)}>{hqBriefs.map(h=><option key={h}>{h}</option>)}</select><Field label='팀원 실행 요청문' value={team} onChange={setTeam}/><Field label='본사 피드백 메시지' value={hq} onChange={setHq}/><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J08-hq',{selectedHqBrief:brief,teamMessage:team,hqFeedback:hq})}>현장 번역 저장</button></Card>}
function OneOnOne({state,save}:any){const m=member(state.selectedMemberId);const[form,setForm]=useState<R>({});return <Card><h2 className='text-xl font-bold'>{m.name} 1on1 코칭</h2><p className='rounded-xl bg-slate-50 p-3'>예상 발언: {m.comment}<br/>위험 문장: {state.riskSentence||'-'}</p>{['대화 시작 문장','코칭 질문 5개','피해야 할 표현 3개','다음 1주 행동 약속','팀장 지원 문장'].map(f=><Field key={f} label={f} value={form[f]} onChange={(v:string)=>setForm({...form,[f]:v})}/>) }<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J09-oneOnOne',{selectedMemberId:m.id,...form})}>1on1 저장</button></Card>}
function Wrap({state,save}:any){const[plan,setPlan]=useState<R>({});const summary=JSON.stringify(state,null,2);return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>앞선 산출물 요약</h2><p>선택 팀원: {member(state.selectedMemberId).name}</p><p>Gap: {(state.gapHypotheses||[]).join(', ')}</p><p>고객군: {(state.customerGroups||[]).join(', ')}</p><pre className='preline mt-3 max-h-72 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{summary}</pre></Card><Card><h2 className='text-xl font-bold'>7일·30일 실행계획</h2>{['7일 실행계획','30일 점검 기준','이해관계자 조율 행동','고객 접점 품질 개선 행동','AI 활용 팀장 원칙'].map(f=><Field key={f} label={f} value={plan[f]} onChange={(v:string)=>setPlan({...plan,[f]:v})}/>) }<button className='mr-2 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={()=>copyText(JSON.stringify({summary:state,plan},null,2))}>전체 결과 복사</button><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={()=>save('J10-finalPlan',{...plan,journeySummary:state,finalText:JSON.stringify(plan)})}>최종 저장</button></Card></div>}

createRoot(document.getElementById('journey-root')!).render(<App/>);
