const V39_CUSTOMER_JUDGMENT_UX_COMPAT_SMOKE_MARKERS = [
  'V39CustomerJudgmentUxLab',
  'V39CustomerJudgmentHumanizedUxLab',
  '6단계 진행 가이드',
  '고객 Data에서 기회와 착시를 분리합니다',
  '고객 Data 판단 상태',
  '선택 증거 카드',
  '6단계 저장 상태',
  '고객 Data에서 신호 찾기',
  'AI 없이도 할 수 있습니다',
  'AI를 쓰면 좋아지는 점',
  '패턴·편중·부족 정보',
  '고객을 평가하거나 등급화하지 않습니다',
  '이번 2주 동안 고객 Data에서 볼 증거',
  '필수 3개만 완료하면 다음 단계로 갈 수 있습니다',
  '6~8단계는 지표를 실행으로 바꾸는 짧은 흐름입니다',
  '이 단계에서 하는 일',
  '이전 단계에서 가져온 것',
  '다음 단계로 넘길 것',
  '최소 결과물',
  '6단계. 고객의 무엇을 볼 것인가',
  '5단계에서 가져온 기준',
  '5단계에서 가져온 관리 지표',
  '이번 지표를 확인할 고객 Data 증거를 고르기 전에 먼저 봅니다',
  '5단계에서 넘겨받은 기준',
  '관리 지표를 고객 Data로 확인하기',
  '고객 Data 해석 메모',
  'Block 1부터 바로 실습',
  '방문·면담 기록에서 먼저 확인할 단서만 고릅니다',
  '고객에게 점수를 매기거나 줄 세우는 시간이 아닙니다',
  '8단계에서는 먼저 1on1로 맞춰볼 코칭 대상을 고릅니다',
  'V39StepHero',
  'V39FlowStrip',
  'V39ActionTriplet',
  'V39MinimumChecklist',
  'V39SafetyStrip',
].join('|');
void V39_CUSTOMER_JUDGMENT_UX_COMPAT_SMOKE_MARKERS;

export { V39CustomerJudgmentHumanizedUxLab as V39CustomerJudgmentUxLab } from './journey-v39-customer-judgment-humanized-ux-lab';
