import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

type R = Record<string, any>;

const WEBAPP_URL = (import.meta.env.VITE_GOOGLE_SCRIPT_WEBAPP_URL || '') as string;
const CP = '실제 병원명, 의료진명, 제품명, 매출·처방 정보는 입력하지 마세요. 본 실습은 교육용 가상 자료만 사용합니다.';

const screens = [
  { id: 'M-P01', module: 'Opening', title: '입장 화면' },
  { id: 'M-P02', module: 'Opening', title: '과정 안내 & AI 활용 원칙' },
  { id: 'M-P03', module: 'M1', title: 'AI 안전선 카드' },
  { id: 'M-P04', module: 'M1', title: '좋은 질문 만들기' },
  { id: 'M-P05', module: 'M2', title: 'MR 활동·성과 Dashboard Lab' },
  { id: 'M-P06', module: 'M2', title: '팀 목표 → MR별 실행행동 Map' },
  { id: 'M-P07', module: 'M3', title: '이해관계자 메시지 번역' },
  { id: 'M-P08', module: 'M3', title: '성과대화 프롬프트 & AI 답변 감별' },
  { id: 'M-P09', module: 'M4', title: '고객관점 콜플랜 실행 요청문' },
  { id: 'M-P10', module: 'M4', title: '본사 요청 → 현장 실행 번역' },
  { id: 'M-P11', module: 'M5', title: 'MR 1on1 코칭 Lab' },
  { id: 'M-P12', module: 'Wrap-up', title: '실행계획 & 결과 요약' }
];

const members = [
  { id: 'M01', name: '신재영 대리', type: '활동량 과다·성과전환 저조형', comment: '저는 누구보다 많이 움직이고 있습니다.', task: '노력을 인정하되 콜 수보다 접점 목적, 고객 반응, 후속조치 품질을 함께 점검한다.', metrics: { 콜실행률: 112, 담당처커버리지: 96, CRM기록충실도: 64, 후속조치율: 58, 고객반응지수: 62, 성과전환지수: 54, 팀기여지수: 61, 실행지연: 2 }, signal: '콜 실행률은 높지만 후속조치율과 성과전환지수가 낮다. 활동량보다 접점 목적과 후속 실행 품질 점검이 필요하다.' },
  { id: 'M02', name: '이대은 대리', type: '고성과 개인플레이형', comment: '각자 자기 담당처는 본인이 책임지는 게 맞지 않나요?', task: '개인 성과를 인정하되 팀 기여 역할과 공유 기준을 구체적으로 요청한다.', metrics: { 콜실행률: 91, 담당처커버리지: 88, CRM기록충실도: 72, 후속조치율: 74, 고객반응지수: 84, 성과전환지수: 128, 팀기여지수: 42, 실행지연: 1 }, signal: '성과전환지수와 고객반응지수는 높지만 팀기여지수가 낮다. 개인성과 인정과 팀 기여 요청의 균형이 필요하다.' },
  { id: 'M03', name: '박재욱 사원', type: '신입 위축형', comment: '제가 가면 오히려 불편해하시는 것 같습니다.', task: '고객 접점 전 준비를 지원하고 작은 성공경험을 설계한다.', metrics: { 콜실행률: 72, 담당처커버리지: 69, CRM기록충실도: 90, 후속조치율: 67, 고객반응지수: 51, 성과전환지수: 48, 팀기여지수: 70, 실행지연: 1 }, signal: 'CRM 기록은 성실하지만 콜 실행률과 고객반응지수가 낮다. 신입 위축과 접점 전 준비 부족 가능성을 확인해야 한다.' },
  { id: 'M04', name: '유희관 과장', type: '경력 안정형', comment: '현장에서는 그런 방식이 잘 안 맞습니다.', task: '경험을 존중하되 본사 요청과 현장 실행 기준을 연결한다.', metrics: { 콜실행률: 86, 담당처커버리지: 92, CRM기록충실도: 55, 후속조치율: 63, 고객반응지수: 76, 성과전환지수: 82, 팀기여지수: 58, 실행지연: 3 }, signal: '담당처 관계와 고객반응은 안정적이나 CRM 기록과 캠페인 실행이 낮다. 변화 요구를 현장 언어로 연결해야 한다.' },
  { id: 'M05', name: '김문호 차장', type: '방어적 목표미달형', comment: '이번 지역 상황은 제가 어떻게 할 수 있는 게 아닙니다.', task: '외부 요인을 인정하되 데이터 기반으로 확인 질문과 다음 행동을 합의한다.', metrics: { 콜실행률: 79, 담당처커버리지: 75, CRM기록충실도: 68, 후속조치율: 61, 고객반응지수: 60, 성과전환지수: 68, 팀기여지수: 55, 실행지연: 5 }, signal: '목표진척과 실행 속도가 모두 낮다. 외부 요인 탓으로 단정하거나 반박하기보다 데이터 기반 공동 진단이 필요하다.' },
  { id: 'M06', name: '김재호 차장', type: '실행지연·CRM 부실형', comment: '현장 대응하느라 입력은 나중에 하게 됩니다.', task: 'CRM 입력을 감시가 아니라 실행 품질과 후속조치 관리 기준으로 설명한다.', metrics: { 콜실행률: 93, 담당처커버리지: 81, CRM기록충실도: 41, 후속조치율: 45, 고객반응지수: 69, 성과전환지수: 73, 팀기여지수: 62, 실행지연: 4 }, signal: '콜 실행은 유지되지만 CRM 기록과 후속조치율이 낮다. 완료 기준과 사후보고 기준 명확화가 필요하다.' }
];

const customers = [
  { id: 'CG-A', label: '고객군 A', frequency: '낮음', response: '높음', followUp: '높음', trustRisk: '중간', growth: '높음', memo: '접점 기회가 부족하지만 반응은 긍정적이다. 후속조치가 적시에 이루어지면 고객 신뢰와 성과전환 가능성이 함께 높아질 수 있다.' },
  { id: 'CG-B', label: '고객군 B', frequency: '높음', response: '낮음', followUp: '낮음', trustRisk: '낮음', growth: '낮음', memo: '접점 빈도는 높지만 반응이 낮다. 단순 방문 횟수보다 접점 목적과 메시지 적합성을 재점검할 필요가 있다.' },
  { id: 'CG-C', label: '고객군 C', frequency: '보통', response: '보통', followUp: '높음', trustRisk: '높음', growth: '보통', memo: '후속조치 지연 시 신뢰 저하 가능성이 높다. 콜 이후 사후관리와 기록 품질 관리가 중요하다.' },
  { id: 'CG-D', label: '고객군 D', frequency: '낮음', response: '보통', followUp: '보통', trustRisk: '낮음', growth: '높음', memo: '현재 접점은 낮지만 성장 가능성이 있다. 무리한 접촉보다 명확한 목적과 고객가치 중심의 접점 설계가 필요하다.' }
];

const stakeholders = [
  { id: 'manager', label: '상사/본부장', expectation: '목표 달성, 실행 속도, 리스크 조기 보고', caution: '현장 사정만 강조하면 변명으로 들릴 수 있음' },
  { id: 'hq', label: '본사 영업기획/SFE', expectation: 'CRM 입력 품질, 활동 데이터 정확성, 캠페인 실행률', caution: '현장 입력 지연과 데이터 관리 피로감' },
  { id: 'team', label: '팀원/MR', expectation: '명확한 방향, 공정한 지원, 현실적인 콜플랜', caution: '목표 압박과 고객 반응 저하에 따른 피로감' },
  { id: 'peer', label: '동료 팀장', expectation: '공유 가능한 운영 기준, 부서 간 협업', caution: '자기 팀만 유리한 방식으로 보일 수 있음' }
];

const hqBriefs = [
  { id: 'HQ1', title: '본사 캠페인 실행 요청', request: '주요 고객군 대상 메시지 전달, 고객 반응 기록, 후속조치 계획 제출', burden: '기존 콜플랜과 일정 충돌, 팀원 피로감 증가', cp: '허가사항 외 표현 금지, 경쟁 제품 비방 금지, 고객 혜택 암시 금지' },
  { id: 'HQ2', title: 'CRM 입력 품질 강화 요청', request: '콜 목적, 고객 반응, 후속조치, 다음 접점 계획 필수 입력', burden: '팀원들이 입력 업무 증가로 인식', cp: '실제 고객정보 외부 AI 입력 금지, 민감한 고객 반응 상세내용 입력 금지' },
  { id: 'HQ3', title: '고객군 우선순위 조정 요청', request: '고객군별 우선순위 재정리, 저반응 고객군 접점 목적 재설계', burden: '팀원별 담당처 운영 방식 변경 필요', cp: '특정 고객 공략 표현 금지, 처방 확대 표현 금지' }
];

const safetyCards = [
  { id: 'SC01', text: '활동량은 많지만 성과전환이 낮은 팀원과 나눌 질문을 만들어줘.', answer: '입력 가능', why: '실제 고객명, 제품명, 매출·처방 정보가 없는 일반화된 리더십 질문이다.' },
  { id: 'SC02', text: '목표 미달 팀원과 면담할 질문을 만들어줘. 실명과 실제 수치는 제외할게.', answer: '익명화 후 가능', why: '실명과 실제 수치를 제외하면 교육용으로 활용 가능하다.' },
  { id: 'SC03', text: 'A병원 김OO 교수의 처방 감소 원인을 분석해줘.', answer: '입력 금지', why: '실제 병원명, 의료진명, 처방 정보가 포함될 수 있어 외부 AI 입력 금지 대상이다.' },
  { id: 'SC04', text: '우리 팀 실제 CRM 데이터를 붙여넣고 팀원별 개선점을 분석해줘.', answer: '입력 금지', why: '실제 고객 접점 정보, 내부 활동 데이터, 팀원 평가정보가 포함될 수 있다.' },
  { id: 'SC05', text: '고객군 A~D라는 가상 데이터로 고객 반응 신호와 후속조치 우선순위를 정리해줘.', answer: '입력 가능', why: '교육용 가상 고객군 데이터이며 실제 고객 정보가 없다.' },
  { id: 'SC06', text: '본사 캠페인 요청을 팀원들에게 어떻게 설명하면 좋을지, 실제 제품명 없이 메시지 초안을 만들어줘.', answer: '익명화 후 가능', why: '실제 제품명과 내부 전략을 제거하고 일반화하면 활용 가능하다.' }
];

const reviewCriteria = ['보안성', 'CP 준수성', '고객가치성', '현장성', '성과책임', '실행가능성', '팀장 역할', '표현 안전성'];
const gapOptions = ['접점 목적 불명확', '후속조치 미흡', '고객군 우선순위 문제', '메시지 일관성 부족', '동기 저하', '팀장 지원 필요'];
const instructionProblems = ['목적 불명확', '완료 기준 없음', '고객가치 부족', '후속조치 없음', 'CRM 기록 기준 없음'];
const sampleAnswers = [
  { type: '좋은 답변', text: '최근 2주 콜 리포트를 보면서 접점 목적, 고객 반응, 후속조치가 어디에서 끊겼는지 함께 확인해보겠습니다. 목표와의 Gap은 분명히 보되, 먼저 막힌 지점을 같이 찾겠습니다.' },
  { type: '위로 과잉형', text: '너무 부담 갖지 말고 천천히 해보세요. 지금도 충분히 잘하고 있으니 성과는 자연스럽게 따라올 것입니다.' },
  { type: '압박 과잉형', text: '목표 미달은 더 이상 용납되기 어렵습니다. 다음 달까지 반드시 수치를 회복해야 합니다.' },
  { type: 'CP 위험형', text: '고객이 관심을 가질 만한 매력적인 제안을 준비해 방문 효과를 높이세요.' }
];

const now = () => new Date().toISOString();
const uid = (prefix: string) => prefix + '-' + Date.now() + '-' + Math.random().toString(36).slice(2, 7);
function getJson<T>(key: string, initial: T): T { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? initial; } catch { return initial; } }
function setJson(key: string, value: any) { localStorage.setItem(key, JSON.stringify(value)); }
function useStore<T>(key: string, initial: T) { const [value, setValue] = useState<T>(() => getJson(key, initial)); useEffect(() => setJson(key, value), [key, value]); return [value, setValue] as const; }
function copyText(text: string) { navigator.clipboard?.writeText(text); }

async function callGoogle(action: string, payload: R = {}) {
  if (!WEBAPP_URL) throw new Error('VITE_GOOGLE_SCRIPT_WEBAPP_URL is not configured');
  const response = await fetch(WEBAPP_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ action, payload }) });
  const result = await response.json();
  if (!result.ok) throw new Error(result.error || 'Google Script request failed');
  return result.data;
}
function pushPending(action: string, payload: R, error: string) { const pending = getJson<any[]>('c1bio_lab_pending_sync', []); pending.push({ id: uid('SYNC'), action, payload, error, createdAt: now(), retryCount: 0 }); setJson('c1bio_lab_pending_sync', pending); }
async function sync(action: string, payload: R, setStatus?: (s: string) => void) { if (!WEBAPP_URL) { setStatus?.('localStorage 모드'); return; } try { await callGoogle(action, payload); setStatus?.('Google Sheets 저장됨'); } catch (error: any) { pushPending(action, payload, String(error?.message || error)); setStatus?.('저장 실패 · pendingSync 보관'); } }
function responsePayload(participant: R, step: number, key: string, value: any) { const screen = screens[step]; return { responseId: uid('R'), participantId: participant.participantId, sessionCode: participant.sessionCode, teamName: participant.teamName, moduleId: screen.module, screenId: screen.id, activityId: key, activityName: screen.title, inputData: value?.inputData || {}, outputData: value, promptText: value?.generatedPrompt || '', aiAnswerText: value?.aiAnswer || '', reviewData: value?.reviewChecks || {}, finalText: value?.finalText || JSON.stringify(value), isCompleted: true, createdAt: now(), updatedAt: now() }; }

function buildPerformancePrompt(member: R) { return `당신은 제약영업팀장의 성과관리와 1on1 대화를 돕는 리더십 코치입니다.\n\n[상황]\n아래 내용은 교육용 가상 자료입니다. 실제 병원명, 의료진명, 제품명, 매출·처방 정보는 포함되어 있지 않습니다.\n대상: ${member.name}\n유형: ${member.type}\n핵심 데이터 신호: ${member.signal}\n팀원이 할 가능성이 있는 말: "${member.comment}"\n\n[요청]\n${member.name}의 노력을 인정하되, 콜 수보다 접점 목적·고객 반응·후속조치 품질을 함께 점검하는 1on1 성과대화 흐름을 작성해주세요.\n\n[조건]\n1. 원인을 단정하지 말고 질문으로 확인해주세요.\n2. 성과 책임을 흐리지 말아주세요.\n3. 고객 공략이나 처방 확대처럼 들릴 수 있는 표현은 피해주세요.\n4. CP 리스크가 있는 표현은 사용하지 말아주세요.\n\n[출력 형식]\n1. 대화 시작 문장\n2. 확인 질문 6개\n3. 피해야 할 표현 3개\n4. 다음 2주 행동 약속\n5. 팀장 지원 문장`; }
function buildStakeholderPrompt() { return `당신은 제약영업팀장의 이해관계자 커뮤니케이션을 돕는 코치입니다.\n\n[상황]\n팀 KPI는 목표 대비 부족하고, 콜 실행률은 높아졌지만 성과전환은 낮습니다. 팀원들은 피로감을 느끼고 있고, 본사는 캠페인 실행과 CRM 기록 품질 강화를 요청하고 있습니다. 고객군 일부에서는 후속조치 지연으로 신뢰 리스크가 보입니다.\n\n[요청]\n같은 상황을 상사, 팀원, 본사 유관부서, 동료 팀장에게 각각 어떻게 다르게 설명하면 좋을지 메시지 초안을 작성해주세요.\n\n[조건]\n변명처럼 들리지 않게 하고, 책임을 전가하지 않으며, 고객가치와 CP 안전선을 반영해주세요.`; }
function buildCallPlanPrompt() { return `당신은 제약영업팀장의 업무관리와 실행정렬을 돕는 코치입니다.\n\n[상황]\n영업팀장이 팀원에게 "이번 주 고객관리 더 신경 써주세요"라고 지시하려고 합니다. 그러나 이 표현은 접점 목적, 고객군 우선순위, 후속조치, 완료 기준이 불명확합니다.\n\n[요청]\n이 모호한 지시를 고객 신뢰, 접점 품질, 후속조치, CRM 기록 기준이 포함된 콜플랜 실행 요청문으로 바꿔주세요.\n\n[조건]\n고객군은 A~D처럼 가상 고객군으로만 표현하고, 실제 병원명, 의료진명, 제품명은 사용하지 마세요.\n\n[출력]\n1. 개선된 업무 요청문\n2. 완료 기준\n3. 중간점검 질문 3개\n4. 팀장 지원 문장`; }
function parseAiAnswer(text: string) { const lines = text.split('\n').map(x => x.trim()).filter(Boolean); return { openingSentence: lines.find(x => x.includes('시작') || x.includes('먼저')) || lines[0] || '', keyQuestions: lines.filter(x => x.includes('?')).slice(0, 6), finalFieldLanguage: lines.slice(-2).join('\n') || text.slice(0, 240) }; }

function Card({ children, className = '' }: any) { return <div className={'rounded-2xl border bg-white p-5 shadow-sm ' + className}>{children}</div>; }
function Notice() { return <div className='safe rounded-xl px-4 py-3 text-sm font-medium'>{CP}</div>; }
function Badge({ children }: any) { return <span className='rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700'>{children}</span>; }
function Field({ label, value, onChange, rows = 3, placeholder = '' }: any) { return <label className='block'><b className='text-sm'>{label}</b><textarea className='mt-1 w-full rounded-xl border p-3 preline' rows={rows} placeholder={placeholder} value={value || ''} onChange={e => onChange(e.target.value)} /></label>; }
function TextInput({ label, value, onChange, placeholder = '' }: any) { return <label className='block'><b className='text-sm'>{label}</b><input className='mt-1 w-full rounded-xl border p-3' placeholder={placeholder} value={value || ''} onChange={e => onChange(e.target.value)} /></label>; }
function SelectBox({ label, value, onChange, options }: any) { return <label className='block'><b className='text-sm'>{label}</b><select className='mt-1 w-full rounded-xl border p-3' value={value} onChange={e => onChange(e.target.value)}>{options.map((o: any) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function MultiButtons({ options, selected = [], onChange }: any) { const toggle = (v: string) => onChange(selected.includes(v) ? selected.filter((x: string) => x !== v) : [...selected, v]); return <div className='flex flex-wrap gap-2'>{options.map((o: string) => <button key={o} className={'rounded-xl border px-3 py-2 text-sm ' + (selected.includes(o) ? 'bg-cyan-700 text-white' : 'bg-white')} onClick={() => toggle(o)}>{o}</button>)}</div>; }
function MetricGrid({ member }: any) { return <div className='grid grid-cols-2 gap-2 md:grid-cols-4'>{Object.entries(member.metrics).map(([k, v]) => <div key={k} className='rounded-xl bg-slate-50 p-3'><p className='text-xs text-slate-500'>{k}</p><b>{String(v)}</b></div>)}</div>; }

function App() { const view = new URLSearchParams(location.search).get('view'); if (view === 'instructor') return <Instructor />; if (view === 'check') return <Check />; return <Learner />; }
function Learner() { const [step, setStep] = useStore('c1bio_step', 0); const [participant, setParticipant] = useStore<R>('c1bio_lab_participant', { participantId: uid('P'), sessionCode: 'C1BIO-1차', name: '', teamName: '' }); const [responses, setResponses] = useStore<R>('c1bio_lab_responses', {}); const [syncStatus, setSyncStatus] = useState('임시저장됨 · localStorage'); const screen = screens[step];
  const save = (key: string, value: any) => { const next = { ...responses, [key]: value }; setResponses(next); sync('saveResponse', responsePayload(participant, step, key, value), setSyncStatus); };
  const next = () => { sync('saveParticipant', { ...participant, role: 'participant', consentChecked: step > 0, createdAt: participant.createdAt || now(), updatedAt: now(), userAgent: navigator.userAgent }, setSyncStatus); sync('saveProgress', { participantId: participant.participantId, sessionCode: participant.sessionCode, teamName: participant.teamName, moduleId: screen.module, status: step >= 11 ? 'completed' : 'in_progress', lastScreenId: screen.id, completedScreenCount: step + 1, totalScreenCount: screens.length, updatedAt: now() }); setStep(Math.min(screens.length - 1, step + 1)); };
  return <div className='mx-auto max-w-7xl p-5'><header className='mb-5 flex flex-wrap items-start justify-between gap-3'><div><h1 className='text-2xl font-bold'>C1바이오 영업팀장 AI 리더십 Development Lab</h1><p className='text-slate-600'>{screen.module} · {screen.title} · {Math.round((step + 1) / screens.length * 100)}%</p></div><div className='flex gap-2'><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => location.href = '/?view=instructor'}>강사용</button><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => location.href = '/?view=check'}>사전점검</button></div></header><Notice /><div className='my-4 h-2 rounded-full bg-slate-200'><div className='h-2 rounded-full bg-cyan-700' style={{ width: ((step + 1) / screens.length * 100) + '%' }} /></div><Screen step={step} participant={participant} setParticipant={setParticipant} save={save} responses={responses} /><footer className='sticky bottom-0 mt-6 flex justify-between rounded-2xl border bg-white/90 p-3'><button className='rounded-xl border px-5 py-3' onClick={() => setStep(Math.max(0, step - 1))}>이전</button><span className='py-3 text-sm text-slate-600'>{syncStatus}</span><button className='rounded-xl bg-cyan-700 px-5 py-3 text-white' onClick={next}>저장하고 다음</button></footer></div>;
}
function Screen({ step, participant, setParticipant, save, responses }: any) { const props = { save, responses }; const list = [<Entry participant={participant} setParticipant={setParticipant} />, <Guide save={save} />, <Safety save={save} />, <BetterPrompt save={save} />, <DashboardLab save={save} />, <BehaviorMap save={save} />, <StakeholderMessage save={save} />, <PerformanceReview save={save} />, <CallPlan save={save} />, <HqTranslation save={save} />, <OneOnOne save={save} />, <ActionPlan save={save} responses={responses} />]; return list[step] || <Card>준비 중</Card>; }
function Entry({ participant, setParticipant }: any) { return <Card><h2 className='text-xl font-bold'>입장 화면</h2><p className='mt-2 text-sm text-slate-600'>교육생 정보를 입력합니다. 실습 중 고객명, 병원명, 제품명은 사용하지 않습니다.</p><div className='mt-4 grid gap-3 md:grid-cols-3'><TextInput label='세션코드' value={participant.sessionCode} onChange={(v: string) => setParticipant({ ...participant, sessionCode: v })} /><TextInput label='이름' value={participant.name} onChange={(v: string) => setParticipant({ ...participant, name: v })} placeholder='본인 이름 또는 교육용 이름' /><TextInput label='팀명' value={participant.teamName} onChange={(v: string) => setParticipant({ ...participant, teamName: v })} placeholder='예: 1조' /></div></Card>; }
function Guide({ save }: any) { return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>오늘의 Journey</h2><p className='mt-2 text-slate-600'>프롬프트 생성 → 외부 AI 복사 → AI 답변 붙여넣기 → CP·현장성 감별 → 현장 언어 수정 → 실행계획 저장</p></Card><div className='grid gap-3 md:grid-cols-3'><Card><h3 className='font-bold'>Data Lens</h3><p>MR 활동·성과 Dashboard와 CRM/SFE Data를 읽고 성과 신호를 해석합니다.</p></Card><Card><h3 className='font-bold'>Stakeholder Lens</h3><p>상사, 본사, 팀원, 동료 팀장의 기대와 긴장을 구분합니다.</p></Card><Card><h3 className='font-bold'>Customer Value Lens</h3><p>고객 신뢰, 접점 품질, 후속조치, CP 안전선 중심으로 실행을 정렬합니다.</p></Card></div><Card><label className='flex gap-2'><input type='checkbox' onChange={e => save('consent', { consentChecked: e.target.checked, consentTimestamp: now() })} /> 위 내용을 확인했습니다.</label></Card></div>; }
function Safety({ save }: any) { const [answers, setAnswers] = useState<R>({}); const choose = (id: string, selected: string) => { const next = { ...answers, [id]: selected }; setAnswers(next); save('safetyCards', { answers: next }); }; return <div className='grid gap-3'>{safetyCards.map((card, i) => <Card key={card.id}><div className='flex items-start justify-between gap-3'><div><Badge>{i + 1}/6</Badge><h3 className='mt-2 font-bold'>{card.text}</h3></div><b className='text-sm text-cyan-700'>{answers[card.id] ? '선택됨' : '미선택'}</b></div><div className='mt-3 flex flex-wrap gap-2'>{['입력 가능', '익명화 후 가능', '입력 금지', '내부 기준 확인 필요'].map(o => <button key={o} className={'rounded-xl border px-3 py-2 text-sm ' + (answers[card.id] === o ? 'bg-cyan-700 text-white' : 'bg-white')} onClick={() => choose(card.id, o)}>{o}</button>)}</div>{answers[card.id] && <p className='mt-3 rounded-xl bg-slate-50 p-3 text-sm'>정답: <b>{card.answer}</b><br />해설: {card.why}</p>}</Card>)}</div>; }
function BetterPrompt({ save }: any) { const bads = ['성과 안 좋은 팀원에게 뭐라고 해야 하나요?', '고객관리 더 신경 쓰라고 말하고 싶은데 어떻게 하죠?', '본사 캠페인을 잘 실행하게 하는 말 만들어줘.', '신입이 자신감이 없어요. 코칭 문장 만들어줘.']; const [selected, setSelected] = useState(bads[0]); const [text, setText] = useState('역할: 당신은 제약영업팀장의 성과관리 코치입니다.\n상황: 교육용 가상 데이터입니다. 실제 병원명, 의료진명, 제품명, 매출·처방 정보는 제외합니다.\n요청: 활동량은 높지만 성과전환이 낮은 팀원과 나눌 확인 질문을 작성해주세요.\n조건: 원인을 단정하지 말고, 고객 신뢰와 후속조치 품질을 반영해주세요.\n출력: 시작 문장, 확인 질문, 피해야 할 표현, 다음 행동 약속'); return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>나쁜 질문 선택</h2>{bads.map(b => <button key={b} className={'mt-2 block w-full rounded-xl border p-3 text-left ' + (selected === b ? 'bg-cyan-50 border-cyan-700' : '')} onClick={() => setSelected(b)}>{b}</button>)}</Card><Card><h2 className='text-xl font-bold'>안전한 프롬프트로 전환</h2><p className='mt-1 text-sm text-slate-600'>역할 / 상황 / 요청 / 조건 / 출력형식을 포함합니다.</p><Field label='개선 프롬프트' rows={12} value={text} onChange={setText} /><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => { copyText(text); save('betterPrompt', { selected, generatedPrompt: text }); }}>프롬프트 복사 및 저장</button></Card></div>; }
function DashboardLab({ save }: any) { const [memberId, setMemberId] = useState(members[0].id); const member = members.find(m => m.id === memberId) || members[0]; const [signals, setSignals] = useState<string[]>([]); const [hypotheses, setHypotheses] = useState<string[]>([]); const [notes, setNotes] = useState(''); const [question, setQuestion] = useState(''); return <div className='grid gap-4'><Card><h2 className='text-xl font-bold'>MR 활동·성과 Dashboard</h2><SelectBox label='우선 확인할 팀원' value={memberId} onChange={setMemberId} options={members.map(m => ({ value: m.id, label: `${m.name} · ${m.type}` }))} /><div className='mt-4'><MetricGrid member={member} /></div><p className='mt-3 rounded-xl bg-slate-50 p-3 text-sm'>{member.signal}</p></Card><div className='grid gap-3 md:grid-cols-4'>{customers.map(c => <Card key={c.id}><h3 className='font-bold'>{c.label}</h3><p className='text-sm'>접점 {c.frequency} · 반응 {c.response}</p><p className='mt-2 text-sm'>{c.memo}</p></Card>)}</div><Card><h3 className='font-bold'>핵심 신호와 Gap 가설</h3><p className='mt-2 text-sm text-slate-600'>낮은 수치로 사람을 단정하지 말고 확인해야 할 신호를 선택합니다.</p><div className='mt-3'><b>핵심 신호 선택</b><MultiButtons options={Object.keys(member.metrics)} selected={signals} onChange={setSignals} /></div><div className='mt-4'><b>가능한 Gap 원인 가설</b><MultiButtons options={gapOptions} selected={hypotheses} onChange={setHypotheses} /></div><Field label='이 데이터만 보고 단정하면 위험한 것' value={notes} onChange={setNotes} /><Field label='확인 질문' value={question} onChange={setQuestion} /><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('dashboardLab', { memberId, selectedSignals: signals, gapHypotheses: hypotheses, cautionNotes: notes, confirmationQuestion: question })}>Dashboard 해석 저장</button></Card></div>; }
function BehaviorMap({ save }: any) { const [memberId, setMemberId] = useState(members[0].id); const member = members.find(m => m.id === memberId) || members[0]; const [form, setForm] = useState<R>({}); const generatedPrompt = `아래 데이터 신호를 2주 실행행동으로 번역해주세요.\n대상: ${member.name}\n신호: ${member.signal}\n조건: 고객 신뢰, 접점 품질, 후속조치, CRM 기록 기준을 포함하고 실제 고객명·제품명은 쓰지 마세요.`; return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>팀원 선택</h2><SelectBox label='팀원' value={memberId} onChange={setMemberId} options={members.map(m => ({ value: m.id, label: m.name }))} /><p className='mt-3 rounded-xl bg-slate-50 p-3'>{member.signal}</p><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>AI 도움 프롬프트 복사</button></Card><Card><h2 className='text-xl font-bold'>2주 실행행동 Map</h2>{['확인할 사실', '필요한 행동', '팀장 지원', '2주 행동 약속'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('behaviorMap', { memberId, dataSignal: member.signal, generatedPrompt, ...form })}>실행행동 Map 저장</button></Card></div>; }
function StakeholderMessage({ save }: any) { const [active, setActive] = useState(stakeholders[0].id); const [messages, setMessages] = useState<R>({}); const [checks, setChecks] = useState<string[]>([]); const st = stakeholders.find(s => s.id === active) || stakeholders[0]; const generatedPrompt = buildStakeholderPrompt(); return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>이해관계자 선택</h2>{stakeholders.map(s => <button key={s.id} className={'mt-2 block w-full rounded-xl border p-3 text-left ' + (active === s.id ? 'border-cyan-700 bg-cyan-50' : '')} onClick={() => setActive(s.id)}><b>{s.label}</b><br /><span className='text-sm'>{s.expectation}</span></button>)}<button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>AI 메시지 번역 프롬프트 복사</button></Card><Card><h2 className='text-xl font-bold'>{st.label} 메시지</h2><p className='rounded-xl bg-slate-50 p-3 text-sm'>주의: {st.caution}</p><Field label='메시지 초안' rows={8} value={messages[active]} onChange={(v: string) => setMessages({ ...messages, [active]: v })} /><b>체크리스트</b><MultiButtons options={['변명처럼 들리지 않음', '책임전가 없음', '고객가치 반영', 'CP 안전선 반영']} selected={checks} onChange={setChecks} /><button className='mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('stakeholderMessage', { messages, checklist: checks, generatedPrompt })}>메시지 저장</button></Card></div>; }
function PerformanceReview({ save }: any) { const [memberId, setMemberId] = useState(members[0].id); const member = members.find(m => m.id === memberId) || members[0]; const [aiAnswer, setAiAnswer] = useState(''); const parsed = useMemo(() => parseAiAnswer(aiAnswer), [aiAnswer]); const [checks, setChecks] = useState<string[]>([]); const [form, setForm] = useState<R>({}); const generatedPrompt = buildPerformancePrompt(member); return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>성과대화 프롬프트</h2><SelectBox label='대상 팀원' value={memberId} onChange={setMemberId} options={members.map(m => ({ value: m.id, label: `${m.name} · ${m.type}` }))} /><pre className='preline mt-3 max-h-80 overflow-auto rounded-xl bg-slate-100 p-3 text-sm'>{generatedPrompt}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>프롬프트 복사</button></Card><Card><h2 className='text-xl font-bold'>AI 답변 감별</h2><div className='mb-2 flex flex-wrap gap-2'>{sampleAnswers.map(s => <button key={s.type} className='rounded-xl border px-3 py-2 text-xs' onClick={() => setAiAnswer(s.text)}>{s.type}</button>)}</div><Field label='AI 답변 원문 붙여넣기' rows={6} value={aiAnswer} onChange={setAiAnswer} /><b>감별 기준</b><MultiButtons options={reviewCriteria} selected={checks} onChange={setChecks} /><div className='mt-3 rounded-xl bg-slate-50 p-3 text-sm'><b>자동 분리 미리보기</b><br />시작 문장: {parsed.openingSentence || '직접 수정 필요'}<br />질문 수: {parsed.keyQuestions.length}</div>{['그대로 쓸 문장', '수정할 문장', '위험 문장', '현장 언어 수정문'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('performanceReview', { memberId, generatedPrompt, aiAnswer, parsed, reviewChecks: checks, ...form })}>감별 결과 저장</button></Card></div>; }
function CallPlan({ save }: any) { const [groups, setGroups] = useState<string[]>([]); const [problems, setProblems] = useState<string[]>([]); const [form, setForm] = useState<R>({}); const generatedPrompt = buildCallPlanPrompt(); return <div className='grid gap-4'><div className='grid gap-3 md:grid-cols-4'>{customers.map(c => <Card key={c.id}><h3 className='font-bold'>{c.label}</h3><p className='text-sm'>{c.memo}</p></Card>)}</div><Card><h2 className='text-xl font-bold'>고객관점 콜플랜 실행 요청문</h2><p className='rounded-xl bg-orange-50 p-3 text-sm'>기존 지시문: “이번 주 고객관리 더 신경 써주세요.”</p><div className='mt-3'><b>우선순위 고객군</b><MultiButtons options={customers.map(c => c.label)} selected={groups} onChange={setGroups} /></div><div className='mt-3'><b>문제점 선택</b><MultiButtons options={instructionProblems} selected={problems} onChange={setProblems} /></div>{['개선된 업무 요청문', '완료 기준', '중간점검 질문 3개', '팀장 지원 문장'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<div className='flex gap-2'><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>AI 도움 프롬프트 복사</button><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('callPlan', { selectedCustomerGroups: groups, instructionProblems: problems, generatedPrompt, ...form })}>콜플랜 요청문 저장</button></div></Card></div>; }
function HqTranslation({ save }: any) { const [briefId, setBriefId] = useState(hqBriefs[0].id); const brief = hqBriefs.find(h => h.id === briefId) || hqBriefs[0]; const [form, setForm] = useState<R>({}); const [checks, setChecks] = useState<string[]>([]); const generatedPrompt = `본사 요청을 현장 실행안으로 번역해주세요.\n요청: ${brief.title}\n내용: ${brief.request}\n현장 부담: ${brief.burden}\nCP 주의: ${brief.cp}\n출력: 본사 요청 해석문, 팀원 실행 요청문, 본사 피드백 메시지`; return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>본사 Brief 선택</h2><SelectBox label='Brief' value={briefId} onChange={setBriefId} options={hqBriefs.map(h => ({ value: h.id, label: h.title }))} /><div className='mt-3 rounded-xl bg-slate-50 p-3 text-sm'><b>요청</b><br />{brief.request}<br /><br /><b>현장 부담</b><br />{brief.burden}<br /><br /><b>CP 주의</b><br />{brief.cp}</div><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>AI 번역 프롬프트 복사</button></Card><Card><h2 className='text-xl font-bold'>현장 실행 번역</h2>{['본사 요청 해석문', '팀원 실행 요청문', '본사 피드백 메시지'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<b>점검 기준</b><MultiButtons options={['책임전가 금지', '현장 수용성', 'CP 안전성', '실행 가능성']} selected={checks} onChange={setChecks} /><button className='mt-3 rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('hqTranslation', { selectedHqBriefId: briefId, generatedPrompt, checklist: checks, ...form })}>본사 요청 번역 저장</button></Card></div>; }
function OneOnOne({ save }: any) { const [memberId, setMemberId] = useState(members[2].id); const member = members.find(m => m.id === memberId) || members[2]; const [purpose, setPurpose] = useState('동기회복'); const [aiAnswer, setAiAnswer] = useState(''); const [form, setForm] = useState<R>({}); const generatedPrompt = `${buildPerformancePrompt(member)}\n\n추가 조건: 대화 목적은 ${purpose}입니다. 다음 1주 행동 약속까지 연결해주세요.`; return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>MR 페르소나 선택</h2><SelectBox label='대상' value={memberId} onChange={setMemberId} options={members.map(m => ({ value: m.id, label: `${m.name} · ${m.type}` }))} /><SelectBox label='대화 목적' value={purpose} onChange={setPurpose} options={['성과대화', '성장지원', '업무정렬', '고객접점 개선', '동기회복'].map(x => ({ value: x, label: x }))} /><p className='mt-3 rounded-xl bg-slate-50 p-3 text-sm'>{member.signal}<br />예상 발언: “{member.comment}”</p><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(generatedPrompt)}>AI 프롬프트 복사</button></Card><Card><h2 className='text-xl font-bold'>1on1 대화 설계</h2><Field label='AI 답변 붙여넣기' rows={4} value={aiAnswer} onChange={setAiAnswer} />{['대화 시작 문장', '코칭 질문 5개', '피해야 할 표현 3개', '다음 1주 행동 약속', '팀장 지원 문장'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('oneOnOne', { selectedPersonaId: memberId, conversationPurpose: purpose, generatedPrompt, aiAnswer, ...form })}>1on1 설계 저장</button></Card></div>; }
function ActionPlan({ save, responses }: any) { const [form, setForm] = useState<R>({}); const summary = JSON.stringify(responses, null, 2); return <div className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-xl font-bold'>7일 실행계획 & 30일 점검</h2>{['7일 실행계획', '30일 점검 기준', '이해관계자 조율 행동', '고객 접점 품질 개선 행동', 'AI 활용 팀장 원칙'].map(f => <Field key={f} label={f} value={form[f]} onChange={(v: string) => setForm({ ...form, [f]: v })} />)}<button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => save('actionPlan', { ...form, finalText: JSON.stringify(form) })}>실행계획 저장</button></Card><Card><h2 className='text-xl font-bold'>전체 결과 요약</h2><pre className='preline max-h-96 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{summary}</pre><button className='mt-3 rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => copyText(summary)}>전체 결과 복사</button></Card></div>; }
function Instructor() { const [responses] = useStore<R>('c1bio_lab_responses', {}); const [pending] = useStore<any[]>('c1bio_lab_pending_sync', []); const keys = Object.keys(responses); return <div className='mx-auto max-w-7xl p-5'><h1 className='text-2xl font-bold'>강사용 대시보드</h1><Notice /><div className='mt-4 grid gap-4 md:grid-cols-4'><Card><b>전체 현황</b><br />응답 화면 수: {keys.length}</Card><Card><b>pendingSync</b><br />{pending.length}건</Card><Card><b>AI 안전선</b><br />혼동 항목 토의용</Card><Card><b>Review</b><br />우수·주의 사례 확인</Card></div><div className='mt-4 grid gap-4 md:grid-cols-2'><Card><h2 className='font-bold'>응답 요약</h2>{keys.map(k => <details key={k} className='mt-2 rounded-xl border p-3'><summary className='cursor-pointer font-semibold'>{k}</summary><pre className='preline mt-2 max-h-72 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{JSON.stringify(responses[k], null, 2)}</pre></details>)}</Card><Card><h2 className='font-bold'>원본 JSON</h2><pre className='preline max-h-[560px] overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{JSON.stringify({ responses, pendingSync: pending }, null, 2)}</pre></Card></div></div>; }
function Check() { const [logs, setLogs] = useState<string[]>([]); const add = (s: string) => setLogs(x => [s, ...x]); async function run(action: string, payload: R = {}) { try { const data = await callGoogle(action, payload); add('✅ ' + action + ' 성공: ' + JSON.stringify(data).slice(0, 180)); } catch (error: any) { add('❌ ' + action + ' 실패: ' + String(error?.message || error)); } } const testP = { participantId: uid('PTEST'), sessionCode: 'C1BIO-1차', name: '사전점검', teamName: '테스트조', role: 'participant', consentChecked: true, createdAt: now(), updatedAt: now(), userAgent: navigator.userAgent }; const testR = { responseId: uid('RTEST'), participantId: testP.participantId, sessionCode: testP.sessionCode, teamName: testP.teamName, moduleId: 'check', screenId: 'CHECK', activityId: 'test-save', activityName: '사전점검 테스트 저장', inputData: { source: 'check' }, outputData: { ok: true }, promptText: '', aiAnswerText: '', reviewData: {}, finalText: 'test', isCompleted: true, createdAt: now(), updatedAt: now() }; return <div className='mx-auto max-w-5xl p-5'><h1 className='text-2xl font-bold'>사전점검 화면</h1><Notice /><div className='mt-4 grid gap-3 md:grid-cols-2'>{[['앱 버전', '2.0.0-content-rich'], ['localStorage', '가능'], ['Google Script URL', WEBAPP_URL ? '설정됨' : '미설정 · localStorage 모드'], ['참여자 앱', '/'], ['강사용', '/?view=instructor']].map(x => <Card key={x[0]}><b>{x[0]}</b><p className='mt-2 text-cyan-800'>{x[1]}</p></Card>)}</div><Card className='mt-4'><h2 className='text-lg font-bold'>Google Sheets 연동 테스트</h2><div className='mt-3 flex flex-wrap gap-2'><button className='rounded-xl bg-slate-900 px-4 py-2 text-white' onClick={() => run('ping')}>ping</button><button className='rounded-xl bg-cyan-700 px-4 py-2 text-white' onClick={() => run('setupSheetsC1Bio')}>setupSheetsC1Bio</button><button className='rounded-xl border px-4 py-2' onClick={() => run('saveParticipant', testP)}>saveParticipant</button><button className='rounded-xl border px-4 py-2' onClick={() => run('saveResponse', testR)}>saveResponse</button><button className='rounded-xl border px-4 py-2' onClick={() => run('getDashboardData', { sessionCode: 'C1BIO-1차' })}>getDashboardData</button></div><pre className='preline mt-3 max-h-80 overflow-auto rounded-xl bg-slate-100 p-3 text-xs'>{logs.join('\n')}</pre></Card></div>; }

createRoot(document.getElementById('root')!).render(<App />);
